/*
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAhnenScopeProvider extends DelegatingScopeProvider {
}
