/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AhnenProposalProvider /* implements AbstractAhnenProposalProvider  */{
  @Override
  public void complete_DATUM(final EObject model, final RuleCall ruleCall, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\nThe method createCompletionProposal(String, ContentAssistContext) is undefined"
      + "\ncomplete_DATUM cannot be resolved");
  }
  
  @Override
  public void complete_VERSION(final EObject model, final RuleCall ruleCall, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\nThe method createCompletionProposal(String, ContentAssistContext) is undefined"
      + "\ncomplete_VERSION cannot be resolved");
  }
}
