/*
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ui;

import com.github.funthomas424242.dsl.ahnen.ui.internal.AhnenActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AhnenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AhnenActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AhnenActivator.getInstance().getInjector(AhnenActivator.COM_GITHUB_FUNTHOMAS424242_DSL_AHNEN);
	}
	
}
