/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.github.funthomas424242.dsl.ahnen.AhnenFactory
 * @model kind="package"
 * @generated
 */
public interface AhnenPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ahnen";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.github.com/funthomas424242/dsl/Ahnen";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ahnen";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AhnenPackage eINSTANCE = com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl.init();

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.ModelImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Datei</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DATEI = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.DateiartImpl <em>Dateiart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.DateiartImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getDateiart()
   * @generated
   */
  int DATEIART = 1;

  /**
   * The feature id for the '<em><b>Buch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATEIART__BUCH = 0;

  /**
   * The feature id for the '<em><b>Familie</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATEIART__FAMILIE = 1;

  /**
   * The number of structural features of the '<em>Dateiart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATEIART_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.FamilieImpl <em>Familie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.FamilieImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getFamilie()
   * @generated
   */
  int FAMILIE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIE__NAME = 0;

  /**
   * The feature id for the '<em><b>Personen</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIE__PERSONEN = 1;

  /**
   * The number of structural features of the '<em>Familie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.PersonImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The feature id for the '<em><b>Letzte Aenderung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__LETZTE_AENDERUNG = 1;

  /**
   * The feature id for the '<em><b>Vorname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__VORNAME = 2;

  /**
   * The feature id for the '<em><b>Mittelname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__MITTELNAME = 3;

  /**
   * The feature id for the '<em><b>Nachname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NACHNAME = 4;

  /**
   * The feature id for the '<em><b>Geburtsname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__GEBURTSNAME = 5;

  /**
   * The feature id for the '<em><b>Rufname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__RUFNAME = 6;

  /**
   * The feature id for the '<em><b>Geschlecht</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__GESCHLECHT = 7;

  /**
   * The feature id for the '<em><b>Geburts Datum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__GEBURTS_DATUM = 8;

  /**
   * The feature id for the '<em><b>Todes Datum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__TODES_DATUM = 9;

  /**
   * The feature id for the '<em><b>Vater</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__VATER = 10;

  /**
   * The feature id for the '<em><b>Mutter</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__MUTTER = 11;

  /**
   * The feature id for the '<em><b>Kinder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__KINDER = 12;

  /**
   * The feature id for the '<em><b>Stiefkinder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__STIEFKINDER = 13;

  /**
   * The feature id for the '<em><b>Beziehungen</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__BEZIEHUNGEN = 14;

  /**
   * The feature id for the '<em><b>Ereignisse</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__EREIGNISSE = 15;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 16;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.EreignisImpl <em>Ereignis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.EreignisImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getEreignis()
   * @generated
   */
  int EREIGNIS = 4;

  /**
   * The feature id for the '<em><b>Von</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EREIGNIS__VON = 0;

  /**
   * The feature id for the '<em><b>Bis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EREIGNIS__BIS = 1;

  /**
   * The number of structural features of the '<em>Ereignis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EREIGNIS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.SchulausbildungImpl <em>Schulausbildung</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.SchulausbildungImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getSchulausbildung()
   * @generated
   */
  int SCHULAUSBILDUNG = 5;

  /**
   * The feature id for the '<em><b>Von</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHULAUSBILDUNG__VON = EREIGNIS__VON;

  /**
   * The feature id for the '<em><b>Bis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHULAUSBILDUNG__BIS = EREIGNIS__BIS;

  /**
   * The feature id for the '<em><b>Abschluss</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHULAUSBILDUNG__ABSCHLUSS = EREIGNIS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Schulausbildung</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHULAUSBILDUNG_FEATURE_COUNT = EREIGNIS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.TaetigkeitImpl <em>Taetigkeit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.TaetigkeitImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getTaetigkeit()
   * @generated
   */
  int TAETIGKEIT = 6;

  /**
   * The feature id for the '<em><b>Von</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAETIGKEIT__VON = EREIGNIS__VON;

  /**
   * The feature id for the '<em><b>Bis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAETIGKEIT__BIS = EREIGNIS__BIS;

  /**
   * The feature id for the '<em><b>Beruf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAETIGKEIT__BERUF = EREIGNIS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Arbeitgeber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAETIGKEIT__ARBEITGEBER = EREIGNIS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ort</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAETIGKEIT__ORT = EREIGNIS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Taetigkeit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAETIGKEIT_FEATURE_COUNT = EREIGNIS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.KinderImpl <em>Kinder</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.KinderImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getKinder()
   * @generated
   */
  int KINDER = 7;

  /**
   * The feature id for the '<em><b>Kind</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KINDER__KIND = 0;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KINDER__NEXT = 1;

  /**
   * The number of structural features of the '<em>Kinder</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KINDER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.BeziehungImpl <em>Beziehung</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.BeziehungImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getBeziehung()
   * @generated
   */
  int BEZIEHUNG = 8;

  /**
   * The feature id for the '<em><b>Beziehung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEZIEHUNG__BEZIEHUNG = 0;

  /**
   * The feature id for the '<em><b>Von Datum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEZIEHUNG__VON_DATUM = 1;

  /**
   * The feature id for the '<em><b>Bis Datum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEZIEHUNG__BIS_DATUM = 2;

  /**
   * The feature id for the '<em><b>Hochzeitstag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEZIEHUNG__HOCHZEITSTAG = 3;

  /**
   * The feature id for the '<em><b>Scheidungstag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEZIEHUNG__SCHEIDUNGSTAG = 4;

  /**
   * The number of structural features of the '<em>Beziehung</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEZIEHUNG_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl <em>Familienbuch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getFamilienbuch()
   * @generated
   */
  int FAMILIENBUCH = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH__NAME = 0;

  /**
   * The feature id for the '<em><b>Familie</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH__FAMILIE = 1;

  /**
   * The feature id for the '<em><b>Person</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH__PERSON = 2;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH__VERSION = 3;

  /**
   * The feature id for the '<em><b>Titel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH__TITEL = 4;

  /**
   * The feature id for the '<em><b>Vorwort</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH__VORWORT = 5;

  /**
   * The feature id for the '<em><b>Autor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH__AUTOR = 6;

  /**
   * The feature id for the '<em><b>Familien</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH__FAMILIEN = 7;

  /**
   * The number of structural features of the '<em>Familienbuch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIENBUCH_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienImportImpl <em>Familien Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.FamilienImportImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getFamilienImport()
   * @generated
   */
  int FAMILIEN_IMPORT = 10;

  /**
   * The feature id for the '<em><b>Familie</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIEN_IMPORT__FAMILIE = 0;

  /**
   * The number of structural features of the '<em>Familien Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAMILIEN_IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.impl.AutorImpl <em>Autor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.impl.AutorImpl
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getAutor()
   * @generated
   */
  int AUTOR = 11;

  /**
   * The feature id for the '<em><b>Vorname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOR__VORNAME = 0;

  /**
   * The feature id for the '<em><b>Nachname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOR__NACHNAME = 1;

  /**
   * The feature id for the '<em><b>Organisations Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOR__ORGANISATIONS_NAME = 2;

  /**
   * The number of structural features of the '<em>Autor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.github.funthomas424242.dsl.ahnen.Geschlecht <em>Geschlecht</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.github.funthomas424242.dsl.ahnen.Geschlecht
   * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getGeschlecht()
   * @generated
   */
  int GESCHLECHT = 12;


  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link com.github.funthomas424242.dsl.ahnen.Model#getDatei <em>Datei</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Datei</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Model#getDatei()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Datei();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Dateiart <em>Dateiart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dateiart</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Dateiart
   * @generated
   */
  EClass getDateiart();

  /**
   * Returns the meta object for the containment reference '{@link com.github.funthomas424242.dsl.ahnen.Dateiart#getBuch <em>Buch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Buch</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Dateiart#getBuch()
   * @see #getDateiart()
   * @generated
   */
  EReference getDateiart_Buch();

  /**
   * Returns the meta object for the containment reference '{@link com.github.funthomas424242.dsl.ahnen.Dateiart#getFamilie <em>Familie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Familie</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Dateiart#getFamilie()
   * @see #getDateiart()
   * @generated
   */
  EReference getDateiart_Familie();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Familie <em>Familie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Familie</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familie
   * @generated
   */
  EClass getFamilie();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Familie#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familie#getName()
   * @see #getFamilie()
   * @generated
   */
  EAttribute getFamilie_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.github.funthomas424242.dsl.ahnen.Familie#getPersonen <em>Personen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Personen</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familie#getPersonen()
   * @see #getFamilie()
   * @generated
   */
  EReference getFamilie_Personen();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getLetzteAenderung <em>Letzte Aenderung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Letzte Aenderung</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getLetzteAenderung()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_LetzteAenderung();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getVorname <em>Vorname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vorname</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getVorname()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Vorname();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getMittelname <em>Mittelname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mittelname</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getMittelname()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Mittelname();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getNachname <em>Nachname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nachname</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getNachname()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Nachname();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getGeburtsname <em>Geburtsname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Geburtsname</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getGeburtsname()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Geburtsname();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getRufname <em>Rufname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rufname</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getRufname()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Rufname();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getGeschlecht <em>Geschlecht</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Geschlecht</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getGeschlecht()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Geschlecht();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getGeburtsDatum <em>Geburts Datum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Geburts Datum</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getGeburtsDatum()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_GeburtsDatum();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Person#getTodesDatum <em>Todes Datum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Todes Datum</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getTodesDatum()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_TodesDatum();

  /**
   * Returns the meta object for the reference '{@link com.github.funthomas424242.dsl.ahnen.Person#getVater <em>Vater</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Vater</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getVater()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Vater();

  /**
   * Returns the meta object for the reference '{@link com.github.funthomas424242.dsl.ahnen.Person#getMutter <em>Mutter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Mutter</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getMutter()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Mutter();

  /**
   * Returns the meta object for the containment reference '{@link com.github.funthomas424242.dsl.ahnen.Person#getKinder <em>Kinder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Kinder</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getKinder()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Kinder();

  /**
   * Returns the meta object for the containment reference '{@link com.github.funthomas424242.dsl.ahnen.Person#getStiefkinder <em>Stiefkinder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stiefkinder</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getStiefkinder()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Stiefkinder();

  /**
   * Returns the meta object for the containment reference list '{@link com.github.funthomas424242.dsl.ahnen.Person#getBeziehungen <em>Beziehungen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Beziehungen</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getBeziehungen()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Beziehungen();

  /**
   * Returns the meta object for the containment reference list '{@link com.github.funthomas424242.dsl.ahnen.Person#getEreignisse <em>Ereignisse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ereignisse</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Person#getEreignisse()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Ereignisse();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Ereignis <em>Ereignis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ereignis</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Ereignis
   * @generated
   */
  EClass getEreignis();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Ereignis#getVon <em>Von</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Von</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Ereignis#getVon()
   * @see #getEreignis()
   * @generated
   */
  EAttribute getEreignis_Von();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Ereignis#getBis <em>Bis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bis</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Ereignis#getBis()
   * @see #getEreignis()
   * @generated
   */
  EAttribute getEreignis_Bis();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Schulausbildung <em>Schulausbildung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schulausbildung</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Schulausbildung
   * @generated
   */
  EClass getSchulausbildung();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Schulausbildung#getAbschluss <em>Abschluss</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Abschluss</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Schulausbildung#getAbschluss()
   * @see #getSchulausbildung()
   * @generated
   */
  EAttribute getSchulausbildung_Abschluss();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit <em>Taetigkeit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Taetigkeit</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Taetigkeit
   * @generated
   */
  EClass getTaetigkeit();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getBeruf <em>Beruf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Beruf</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Taetigkeit#getBeruf()
   * @see #getTaetigkeit()
   * @generated
   */
  EAttribute getTaetigkeit_Beruf();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getArbeitgeber <em>Arbeitgeber</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arbeitgeber</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Taetigkeit#getArbeitgeber()
   * @see #getTaetigkeit()
   * @generated
   */
  EAttribute getTaetigkeit_Arbeitgeber();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getOrt <em>Ort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ort</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Taetigkeit#getOrt()
   * @see #getTaetigkeit()
   * @generated
   */
  EAttribute getTaetigkeit_Ort();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Kinder <em>Kinder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Kinder</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Kinder
   * @generated
   */
  EClass getKinder();

  /**
   * Returns the meta object for the reference '{@link com.github.funthomas424242.dsl.ahnen.Kinder#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Kind</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Kinder#getKind()
   * @see #getKinder()
   * @generated
   */
  EReference getKinder_Kind();

  /**
   * Returns the meta object for the containment reference '{@link com.github.funthomas424242.dsl.ahnen.Kinder#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Next</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Kinder#getNext()
   * @see #getKinder()
   * @generated
   */
  EReference getKinder_Next();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Beziehung <em>Beziehung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Beziehung</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Beziehung
   * @generated
   */
  EClass getBeziehung();

  /**
   * Returns the meta object for the reference '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getBeziehung <em>Beziehung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Beziehung</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Beziehung#getBeziehung()
   * @see #getBeziehung()
   * @generated
   */
  EReference getBeziehung_Beziehung();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getVonDatum <em>Von Datum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Von Datum</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Beziehung#getVonDatum()
   * @see #getBeziehung()
   * @generated
   */
  EAttribute getBeziehung_VonDatum();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getBisDatum <em>Bis Datum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bis Datum</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Beziehung#getBisDatum()
   * @see #getBeziehung()
   * @generated
   */
  EAttribute getBeziehung_BisDatum();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getHochzeitstag <em>Hochzeitstag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hochzeitstag</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Beziehung#getHochzeitstag()
   * @see #getBeziehung()
   * @generated
   */
  EAttribute getBeziehung_Hochzeitstag();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getScheidungstag <em>Scheidungstag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scheidungstag</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Beziehung#getScheidungstag()
   * @see #getBeziehung()
   * @generated
   */
  EAttribute getBeziehung_Scheidungstag();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch <em>Familienbuch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Familienbuch</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch
   * @generated
   */
  EClass getFamilienbuch();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch#getName()
   * @see #getFamilienbuch()
   * @generated
   */
  EAttribute getFamilienbuch_Name();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getFamilie <em>Familie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Familie</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch#getFamilie()
   * @see #getFamilienbuch()
   * @generated
   */
  EAttribute getFamilienbuch_Familie();

  /**
   * Returns the meta object for the reference '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getPerson <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Person</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch#getPerson()
   * @see #getFamilienbuch()
   * @generated
   */
  EReference getFamilienbuch_Person();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch#getVersion()
   * @see #getFamilienbuch()
   * @generated
   */
  EAttribute getFamilienbuch_Version();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getTitel <em>Titel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Titel</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch#getTitel()
   * @see #getFamilienbuch()
   * @generated
   */
  EAttribute getFamilienbuch_Titel();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getVorwort <em>Vorwort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vorwort</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch#getVorwort()
   * @see #getFamilienbuch()
   * @generated
   */
  EAttribute getFamilienbuch_Vorwort();

  /**
   * Returns the meta object for the containment reference '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getAutor <em>Autor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Autor</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch#getAutor()
   * @see #getFamilienbuch()
   * @generated
   */
  EReference getFamilienbuch_Autor();

  /**
   * Returns the meta object for the containment reference list '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getFamilien <em>Familien</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Familien</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Familienbuch#getFamilien()
   * @see #getFamilienbuch()
   * @generated
   */
  EReference getFamilienbuch_Familien();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.FamilienImport <em>Familien Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Familien Import</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.FamilienImport
   * @generated
   */
  EClass getFamilienImport();

  /**
   * Returns the meta object for the reference '{@link com.github.funthomas424242.dsl.ahnen.FamilienImport#getFamilie <em>Familie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Familie</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.FamilienImport#getFamilie()
   * @see #getFamilienImport()
   * @generated
   */
  EReference getFamilienImport_Familie();

  /**
   * Returns the meta object for class '{@link com.github.funthomas424242.dsl.ahnen.Autor <em>Autor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Autor</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Autor
   * @generated
   */
  EClass getAutor();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Autor#getVorname <em>Vorname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vorname</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Autor#getVorname()
   * @see #getAutor()
   * @generated
   */
  EAttribute getAutor_Vorname();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Autor#getNachname <em>Nachname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nachname</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Autor#getNachname()
   * @see #getAutor()
   * @generated
   */
  EAttribute getAutor_Nachname();

  /**
   * Returns the meta object for the attribute '{@link com.github.funthomas424242.dsl.ahnen.Autor#getOrganisationsName <em>Organisations Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Organisations Name</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Autor#getOrganisationsName()
   * @see #getAutor()
   * @generated
   */
  EAttribute getAutor_OrganisationsName();

  /**
   * Returns the meta object for enum '{@link com.github.funthomas424242.dsl.ahnen.Geschlecht <em>Geschlecht</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Geschlecht</em>'.
   * @see com.github.funthomas424242.dsl.ahnen.Geschlecht
   * @generated
   */
  EEnum getGeschlecht();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AhnenFactory getAhnenFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.ModelImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Datei</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DATEI = eINSTANCE.getModel_Datei();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.DateiartImpl <em>Dateiart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.DateiartImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getDateiart()
     * @generated
     */
    EClass DATEIART = eINSTANCE.getDateiart();

    /**
     * The meta object literal for the '<em><b>Buch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATEIART__BUCH = eINSTANCE.getDateiart_Buch();

    /**
     * The meta object literal for the '<em><b>Familie</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATEIART__FAMILIE = eINSTANCE.getDateiart_Familie();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.FamilieImpl <em>Familie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.FamilieImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getFamilie()
     * @generated
     */
    EClass FAMILIE = eINSTANCE.getFamilie();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FAMILIE__NAME = eINSTANCE.getFamilie_Name();

    /**
     * The meta object literal for the '<em><b>Personen</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAMILIE__PERSONEN = eINSTANCE.getFamilie_Personen();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.PersonImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '<em><b>Letzte Aenderung</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__LETZTE_AENDERUNG = eINSTANCE.getPerson_LetzteAenderung();

    /**
     * The meta object literal for the '<em><b>Vorname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__VORNAME = eINSTANCE.getPerson_Vorname();

    /**
     * The meta object literal for the '<em><b>Mittelname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__MITTELNAME = eINSTANCE.getPerson_Mittelname();

    /**
     * The meta object literal for the '<em><b>Nachname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NACHNAME = eINSTANCE.getPerson_Nachname();

    /**
     * The meta object literal for the '<em><b>Geburtsname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__GEBURTSNAME = eINSTANCE.getPerson_Geburtsname();

    /**
     * The meta object literal for the '<em><b>Rufname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__RUFNAME = eINSTANCE.getPerson_Rufname();

    /**
     * The meta object literal for the '<em><b>Geschlecht</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__GESCHLECHT = eINSTANCE.getPerson_Geschlecht();

    /**
     * The meta object literal for the '<em><b>Geburts Datum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__GEBURTS_DATUM = eINSTANCE.getPerson_GeburtsDatum();

    /**
     * The meta object literal for the '<em><b>Todes Datum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__TODES_DATUM = eINSTANCE.getPerson_TodesDatum();

    /**
     * The meta object literal for the '<em><b>Vater</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__VATER = eINSTANCE.getPerson_Vater();

    /**
     * The meta object literal for the '<em><b>Mutter</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__MUTTER = eINSTANCE.getPerson_Mutter();

    /**
     * The meta object literal for the '<em><b>Kinder</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__KINDER = eINSTANCE.getPerson_Kinder();

    /**
     * The meta object literal for the '<em><b>Stiefkinder</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__STIEFKINDER = eINSTANCE.getPerson_Stiefkinder();

    /**
     * The meta object literal for the '<em><b>Beziehungen</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__BEZIEHUNGEN = eINSTANCE.getPerson_Beziehungen();

    /**
     * The meta object literal for the '<em><b>Ereignisse</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__EREIGNISSE = eINSTANCE.getPerson_Ereignisse();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.EreignisImpl <em>Ereignis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.EreignisImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getEreignis()
     * @generated
     */
    EClass EREIGNIS = eINSTANCE.getEreignis();

    /**
     * The meta object literal for the '<em><b>Von</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EREIGNIS__VON = eINSTANCE.getEreignis_Von();

    /**
     * The meta object literal for the '<em><b>Bis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EREIGNIS__BIS = eINSTANCE.getEreignis_Bis();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.SchulausbildungImpl <em>Schulausbildung</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.SchulausbildungImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getSchulausbildung()
     * @generated
     */
    EClass SCHULAUSBILDUNG = eINSTANCE.getSchulausbildung();

    /**
     * The meta object literal for the '<em><b>Abschluss</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHULAUSBILDUNG__ABSCHLUSS = eINSTANCE.getSchulausbildung_Abschluss();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.TaetigkeitImpl <em>Taetigkeit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.TaetigkeitImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getTaetigkeit()
     * @generated
     */
    EClass TAETIGKEIT = eINSTANCE.getTaetigkeit();

    /**
     * The meta object literal for the '<em><b>Beruf</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAETIGKEIT__BERUF = eINSTANCE.getTaetigkeit_Beruf();

    /**
     * The meta object literal for the '<em><b>Arbeitgeber</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAETIGKEIT__ARBEITGEBER = eINSTANCE.getTaetigkeit_Arbeitgeber();

    /**
     * The meta object literal for the '<em><b>Ort</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAETIGKEIT__ORT = eINSTANCE.getTaetigkeit_Ort();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.KinderImpl <em>Kinder</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.KinderImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getKinder()
     * @generated
     */
    EClass KINDER = eINSTANCE.getKinder();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KINDER__KIND = eINSTANCE.getKinder_Kind();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KINDER__NEXT = eINSTANCE.getKinder_Next();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.BeziehungImpl <em>Beziehung</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.BeziehungImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getBeziehung()
     * @generated
     */
    EClass BEZIEHUNG = eINSTANCE.getBeziehung();

    /**
     * The meta object literal for the '<em><b>Beziehung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEZIEHUNG__BEZIEHUNG = eINSTANCE.getBeziehung_Beziehung();

    /**
     * The meta object literal for the '<em><b>Von Datum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEZIEHUNG__VON_DATUM = eINSTANCE.getBeziehung_VonDatum();

    /**
     * The meta object literal for the '<em><b>Bis Datum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEZIEHUNG__BIS_DATUM = eINSTANCE.getBeziehung_BisDatum();

    /**
     * The meta object literal for the '<em><b>Hochzeitstag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEZIEHUNG__HOCHZEITSTAG = eINSTANCE.getBeziehung_Hochzeitstag();

    /**
     * The meta object literal for the '<em><b>Scheidungstag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEZIEHUNG__SCHEIDUNGSTAG = eINSTANCE.getBeziehung_Scheidungstag();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl <em>Familienbuch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getFamilienbuch()
     * @generated
     */
    EClass FAMILIENBUCH = eINSTANCE.getFamilienbuch();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FAMILIENBUCH__NAME = eINSTANCE.getFamilienbuch_Name();

    /**
     * The meta object literal for the '<em><b>Familie</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FAMILIENBUCH__FAMILIE = eINSTANCE.getFamilienbuch_Familie();

    /**
     * The meta object literal for the '<em><b>Person</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAMILIENBUCH__PERSON = eINSTANCE.getFamilienbuch_Person();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FAMILIENBUCH__VERSION = eINSTANCE.getFamilienbuch_Version();

    /**
     * The meta object literal for the '<em><b>Titel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FAMILIENBUCH__TITEL = eINSTANCE.getFamilienbuch_Titel();

    /**
     * The meta object literal for the '<em><b>Vorwort</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FAMILIENBUCH__VORWORT = eINSTANCE.getFamilienbuch_Vorwort();

    /**
     * The meta object literal for the '<em><b>Autor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAMILIENBUCH__AUTOR = eINSTANCE.getFamilienbuch_Autor();

    /**
     * The meta object literal for the '<em><b>Familien</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAMILIENBUCH__FAMILIEN = eINSTANCE.getFamilienbuch_Familien();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienImportImpl <em>Familien Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.FamilienImportImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getFamilienImport()
     * @generated
     */
    EClass FAMILIEN_IMPORT = eINSTANCE.getFamilienImport();

    /**
     * The meta object literal for the '<em><b>Familie</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAMILIEN_IMPORT__FAMILIE = eINSTANCE.getFamilienImport_Familie();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.impl.AutorImpl <em>Autor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.impl.AutorImpl
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getAutor()
     * @generated
     */
    EClass AUTOR = eINSTANCE.getAutor();

    /**
     * The meta object literal for the '<em><b>Vorname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTOR__VORNAME = eINSTANCE.getAutor_Vorname();

    /**
     * The meta object literal for the '<em><b>Nachname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTOR__NACHNAME = eINSTANCE.getAutor_Nachname();

    /**
     * The meta object literal for the '<em><b>Organisations Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTOR__ORGANISATIONS_NAME = eINSTANCE.getAutor_OrganisationsName();

    /**
     * The meta object literal for the '{@link com.github.funthomas424242.dsl.ahnen.Geschlecht <em>Geschlecht</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.github.funthomas424242.dsl.ahnen.Geschlecht
     * @see com.github.funthomas424242.dsl.ahnen.impl.AhnenPackageImpl#getGeschlecht()
     * @generated
     */
    EEnum GESCHLECHT = eINSTANCE.getGeschlecht();

  }

} //AhnenPackage
