/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage
 * @generated
 */
public interface AhnenFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AhnenFactory eINSTANCE = com.github.funthomas424242.dsl.ahnen.impl.AhnenFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Dateiart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dateiart</em>'.
   * @generated
   */
  Dateiart createDateiart();

  /**
   * Returns a new object of class '<em>Familie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Familie</em>'.
   * @generated
   */
  Familie createFamilie();

  /**
   * Returns a new object of class '<em>Person</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person</em>'.
   * @generated
   */
  Person createPerson();

  /**
   * Returns a new object of class '<em>Ereignis</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ereignis</em>'.
   * @generated
   */
  Ereignis createEreignis();

  /**
   * Returns a new object of class '<em>Schulausbildung</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Schulausbildung</em>'.
   * @generated
   */
  Schulausbildung createSchulausbildung();

  /**
   * Returns a new object of class '<em>Taetigkeit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Taetigkeit</em>'.
   * @generated
   */
  Taetigkeit createTaetigkeit();

  /**
   * Returns a new object of class '<em>Kinder</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Kinder</em>'.
   * @generated
   */
  Kinder createKinder();

  /**
   * Returns a new object of class '<em>Beziehung</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Beziehung</em>'.
   * @generated
   */
  Beziehung createBeziehung();

  /**
   * Returns a new object of class '<em>Familienbuch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Familienbuch</em>'.
   * @generated
   */
  Familienbuch createFamilienbuch();

  /**
   * Returns a new object of class '<em>Familien Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Familien Import</em>'.
   * @generated
   */
  FamilienImport createFamilienImport();

  /**
   * Returns a new object of class '<em>Autor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Autor</em>'.
   * @generated
   */
  Autor createAutor();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AhnenPackage getAhnenPackage();

} //AhnenFactory
