/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Autor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Autor#getVorname <em>Vorname</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Autor#getNachname <em>Nachname</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Autor#getOrganisationsName <em>Organisations Name</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getAutor()
 * @model
 * @generated
 */
public interface Autor extends EObject
{
  /**
   * Returns the value of the '<em><b>Vorname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vorname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vorname</em>' attribute.
   * @see #setVorname(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getAutor_Vorname()
   * @model
   * @generated
   */
  String getVorname();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Autor#getVorname <em>Vorname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vorname</em>' attribute.
   * @see #getVorname()
   * @generated
   */
  void setVorname(String value);

  /**
   * Returns the value of the '<em><b>Nachname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nachname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nachname</em>' attribute.
   * @see #setNachname(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getAutor_Nachname()
   * @model
   * @generated
   */
  String getNachname();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Autor#getNachname <em>Nachname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nachname</em>' attribute.
   * @see #getNachname()
   * @generated
   */
  void setNachname(String value);

  /**
   * Returns the value of the '<em><b>Organisations Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Organisations Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Organisations Name</em>' attribute.
   * @see #setOrganisationsName(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getAutor_OrganisationsName()
   * @model
   * @generated
   */
  String getOrganisationsName();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Autor#getOrganisationsName <em>Organisations Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Organisations Name</em>' attribute.
   * @see #getOrganisationsName()
   * @generated
   */
  void setOrganisationsName(String value);

} // Autor
