/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Beziehung</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getBeziehung <em>Beziehung</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getVonDatum <em>Von Datum</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getBisDatum <em>Bis Datum</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getHochzeitstag <em>Hochzeitstag</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getScheidungstag <em>Scheidungstag</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getBeziehung()
 * @model
 * @generated
 */
public interface Beziehung extends EObject
{
  /**
   * Returns the value of the '<em><b>Beziehung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Beziehung</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beziehung</em>' reference.
   * @see #setBeziehung(Person)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getBeziehung_Beziehung()
   * @model
   * @generated
   */
  Person getBeziehung();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getBeziehung <em>Beziehung</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Beziehung</em>' reference.
   * @see #getBeziehung()
   * @generated
   */
  void setBeziehung(Person value);

  /**
   * Returns the value of the '<em><b>Von Datum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Von Datum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Von Datum</em>' attribute.
   * @see #setVonDatum(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getBeziehung_VonDatum()
   * @model
   * @generated
   */
  String getVonDatum();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getVonDatum <em>Von Datum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Von Datum</em>' attribute.
   * @see #getVonDatum()
   * @generated
   */
  void setVonDatum(String value);

  /**
   * Returns the value of the '<em><b>Bis Datum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bis Datum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bis Datum</em>' attribute.
   * @see #setBisDatum(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getBeziehung_BisDatum()
   * @model
   * @generated
   */
  String getBisDatum();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getBisDatum <em>Bis Datum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bis Datum</em>' attribute.
   * @see #getBisDatum()
   * @generated
   */
  void setBisDatum(String value);

  /**
   * Returns the value of the '<em><b>Hochzeitstag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hochzeitstag</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hochzeitstag</em>' attribute.
   * @see #setHochzeitstag(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getBeziehung_Hochzeitstag()
   * @model
   * @generated
   */
  String getHochzeitstag();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getHochzeitstag <em>Hochzeitstag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hochzeitstag</em>' attribute.
   * @see #getHochzeitstag()
   * @generated
   */
  void setHochzeitstag(String value);

  /**
   * Returns the value of the '<em><b>Scheidungstag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scheidungstag</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scheidungstag</em>' attribute.
   * @see #setScheidungstag(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getBeziehung_Scheidungstag()
   * @model
   * @generated
   */
  String getScheidungstag();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Beziehung#getScheidungstag <em>Scheidungstag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scheidungstag</em>' attribute.
   * @see #getScheidungstag()
   * @generated
   */
  void setScheidungstag(String value);

} // Beziehung
