/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ereignis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Ereignis#getVon <em>Von</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Ereignis#getBis <em>Bis</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getEreignis()
 * @model
 * @generated
 */
public interface Ereignis extends EObject
{
  /**
   * Returns the value of the '<em><b>Von</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Von</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Von</em>' attribute.
   * @see #setVon(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getEreignis_Von()
   * @model
   * @generated
   */
  String getVon();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Ereignis#getVon <em>Von</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Von</em>' attribute.
   * @see #getVon()
   * @generated
   */
  void setVon(String value);

  /**
   * Returns the value of the '<em><b>Bis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bis</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bis</em>' attribute.
   * @see #setBis(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getEreignis_Bis()
   * @model
   * @generated
   */
  String getBis();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Ereignis#getBis <em>Bis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bis</em>' attribute.
   * @see #getBis()
   * @generated
   */
  void setBis(String value);

} // Ereignis
