/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Familien Import</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.FamilienImport#getFamilie <em>Familie</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienImport()
 * @model
 * @generated
 */
public interface FamilienImport extends EObject
{
  /**
   * Returns the value of the '<em><b>Familie</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Familie</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Familie</em>' reference.
   * @see #setFamilie(Familie)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienImport_Familie()
   * @model
   * @generated
   */
  Familie getFamilie();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.FamilienImport#getFamilie <em>Familie</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Familie</em>' reference.
   * @see #getFamilie()
   * @generated
   */
  void setFamilie(Familie value);

} // FamilienImport
