/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Familienbuch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getName <em>Name</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getFamilie <em>Familie</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getPerson <em>Person</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getVersion <em>Version</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getTitel <em>Titel</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getVorwort <em>Vorwort</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getAutor <em>Autor</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getFamilien <em>Familien</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch()
 * @model
 * @generated
 */
public interface Familienbuch extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Familie</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Familie</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Familie</em>' attribute.
   * @see #setFamilie(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch_Familie()
   * @model
   * @generated
   */
  String getFamilie();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getFamilie <em>Familie</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Familie</em>' attribute.
   * @see #getFamilie()
   * @generated
   */
  void setFamilie(String value);

  /**
   * Returns the value of the '<em><b>Person</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Person</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person</em>' reference.
   * @see #setPerson(Person)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch_Person()
   * @model
   * @generated
   */
  Person getPerson();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getPerson <em>Person</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Person</em>' reference.
   * @see #getPerson()
   * @generated
   */
  void setPerson(Person value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Version</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Titel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Titel</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titel</em>' attribute.
   * @see #setTitel(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch_Titel()
   * @model
   * @generated
   */
  String getTitel();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getTitel <em>Titel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titel</em>' attribute.
   * @see #getTitel()
   * @generated
   */
  void setTitel(String value);

  /**
   * Returns the value of the '<em><b>Vorwort</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vorwort</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vorwort</em>' attribute.
   * @see #setVorwort(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch_Vorwort()
   * @model
   * @generated
   */
  String getVorwort();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getVorwort <em>Vorwort</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vorwort</em>' attribute.
   * @see #getVorwort()
   * @generated
   */
  void setVorwort(String value);

  /**
   * Returns the value of the '<em><b>Autor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Autor</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Autor</em>' containment reference.
   * @see #setAutor(Autor)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch_Autor()
   * @model containment="true"
   * @generated
   */
  Autor getAutor();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Familienbuch#getAutor <em>Autor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Autor</em>' containment reference.
   * @see #getAutor()
   * @generated
   */
  void setAutor(Autor value);

  /**
   * Returns the value of the '<em><b>Familien</b></em>' containment reference list.
   * The list contents are of type {@link com.github.funthomas424242.dsl.ahnen.FamilienImport}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Familien</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Familien</em>' containment reference list.
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilienbuch_Familien()
   * @model containment="true"
   * @generated
   */
  EList<FamilienImport> getFamilien();

} // Familienbuch
