/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Familie</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familie#getName <em>Name</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Familie#getPersonen <em>Personen</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilie()
 * @model
 * @generated
 */
public interface Familie extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilie_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Familie#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Personen</b></em>' containment reference list.
   * The list contents are of type {@link com.github.funthomas424242.dsl.ahnen.Person}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Personen</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Personen</em>' containment reference list.
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getFamilie_Personen()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPersonen();

} // Familie
