/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Geschlecht</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getGeschlecht()
 * @model
 * @generated
 */
public enum Geschlecht implements Enumerator
{
  /**
   * The '<em><b>Unbekannt</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNBEKANNT_VALUE
   * @generated
   * @ordered
   */
  UNBEKANNT(0, "unbekannt", "unbekannt"),

  /**
   * The '<em><b>Maennlich</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAENNLICH_VALUE
   * @generated
   * @ordered
   */
  MAENNLICH(1, "maennlich", "m\u00e4nnlich"),

  /**
   * The '<em><b>Weiblich</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEIBLICH_VALUE
   * @generated
   * @ordered
   */
  WEIBLICH(2, "weiblich", "weiblich");

  /**
   * The '<em><b>Unbekannt</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Unbekannt</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #UNBEKANNT
   * @model name="unbekannt"
   * @generated
   * @ordered
   */
  public static final int UNBEKANNT_VALUE = 0;

  /**
   * The '<em><b>Maennlich</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Maennlich</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MAENNLICH
   * @model name="maennlich" literal="m\344nnlich"
   * @generated
   * @ordered
   */
  public static final int MAENNLICH_VALUE = 1;

  /**
   * The '<em><b>Weiblich</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Weiblich</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEIBLICH
   * @model name="weiblich"
   * @generated
   * @ordered
   */
  public static final int WEIBLICH_VALUE = 2;

  /**
   * An array of all the '<em><b>Geschlecht</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Geschlecht[] VALUES_ARRAY =
    new Geschlecht[]
    {
      UNBEKANNT,
      MAENNLICH,
      WEIBLICH,
    };

  /**
   * A public read-only list of all the '<em><b>Geschlecht</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Geschlecht> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Geschlecht</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Geschlecht get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Geschlecht result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Geschlecht</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Geschlecht getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Geschlecht result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Geschlecht</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Geschlecht get(int value)
  {
    switch (value)
    {
      case UNBEKANNT_VALUE: return UNBEKANNT;
      case MAENNLICH_VALUE: return MAENNLICH;
      case WEIBLICH_VALUE: return WEIBLICH;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Geschlecht(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Geschlecht
