/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Kinder</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Kinder#getKind <em>Kind</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Kinder#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getKinder()
 * @model
 * @generated
 */
public interface Kinder extends EObject
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kind</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' reference.
   * @see #setKind(Person)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getKinder_Kind()
   * @model
   * @generated
   */
  Person getKind();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Kinder#getKind <em>Kind</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' reference.
   * @see #getKind()
   * @generated
   */
  void setKind(Person value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Next</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference.
   * @see #setNext(Kinder)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getKinder_Next()
   * @model containment="true"
   * @generated
   */
  Kinder getNext();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Kinder#getNext <em>Next</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' containment reference.
   * @see #getNext()
   * @generated
   */
  void setNext(Kinder value);

} // Kinder
