/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getName <em>Name</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getLetzteAenderung <em>Letzte Aenderung</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getVorname <em>Vorname</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getMittelname <em>Mittelname</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getNachname <em>Nachname</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getGeburtsname <em>Geburtsname</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getRufname <em>Rufname</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getGeschlecht <em>Geschlecht</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getGeburtsDatum <em>Geburts Datum</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getTodesDatum <em>Todes Datum</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getVater <em>Vater</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getMutter <em>Mutter</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getKinder <em>Kinder</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getStiefkinder <em>Stiefkinder</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getBeziehungen <em>Beziehungen</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Person#getEreignisse <em>Ereignisse</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson()
 * @model
 * @generated
 */
public interface Person extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Letzte Aenderung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Letzte Aenderung</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Letzte Aenderung</em>' attribute.
   * @see #setLetzteAenderung(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_LetzteAenderung()
   * @model
   * @generated
   */
  String getLetzteAenderung();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getLetzteAenderung <em>Letzte Aenderung</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Letzte Aenderung</em>' attribute.
   * @see #getLetzteAenderung()
   * @generated
   */
  void setLetzteAenderung(String value);

  /**
   * Returns the value of the '<em><b>Vorname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vorname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vorname</em>' attribute.
   * @see #setVorname(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Vorname()
   * @model
   * @generated
   */
  String getVorname();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getVorname <em>Vorname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vorname</em>' attribute.
   * @see #getVorname()
   * @generated
   */
  void setVorname(String value);

  /**
   * Returns the value of the '<em><b>Mittelname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mittelname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mittelname</em>' attribute.
   * @see #setMittelname(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Mittelname()
   * @model
   * @generated
   */
  String getMittelname();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getMittelname <em>Mittelname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mittelname</em>' attribute.
   * @see #getMittelname()
   * @generated
   */
  void setMittelname(String value);

  /**
   * Returns the value of the '<em><b>Nachname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nachname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nachname</em>' attribute.
   * @see #setNachname(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Nachname()
   * @model
   * @generated
   */
  String getNachname();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getNachname <em>Nachname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nachname</em>' attribute.
   * @see #getNachname()
   * @generated
   */
  void setNachname(String value);

  /**
   * Returns the value of the '<em><b>Geburtsname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Geburtsname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Geburtsname</em>' attribute.
   * @see #setGeburtsname(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Geburtsname()
   * @model
   * @generated
   */
  String getGeburtsname();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getGeburtsname <em>Geburtsname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Geburtsname</em>' attribute.
   * @see #getGeburtsname()
   * @generated
   */
  void setGeburtsname(String value);

  /**
   * Returns the value of the '<em><b>Rufname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rufname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rufname</em>' attribute.
   * @see #setRufname(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Rufname()
   * @model
   * @generated
   */
  String getRufname();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getRufname <em>Rufname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rufname</em>' attribute.
   * @see #getRufname()
   * @generated
   */
  void setRufname(String value);

  /**
   * Returns the value of the '<em><b>Geschlecht</b></em>' attribute.
   * The literals are from the enumeration {@link com.github.funthomas424242.dsl.ahnen.Geschlecht}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Geschlecht</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Geschlecht</em>' attribute.
   * @see com.github.funthomas424242.dsl.ahnen.Geschlecht
   * @see #setGeschlecht(Geschlecht)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Geschlecht()
   * @model
   * @generated
   */
  Geschlecht getGeschlecht();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getGeschlecht <em>Geschlecht</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Geschlecht</em>' attribute.
   * @see com.github.funthomas424242.dsl.ahnen.Geschlecht
   * @see #getGeschlecht()
   * @generated
   */
  void setGeschlecht(Geschlecht value);

  /**
   * Returns the value of the '<em><b>Geburts Datum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Geburts Datum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Geburts Datum</em>' attribute.
   * @see #setGeburtsDatum(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_GeburtsDatum()
   * @model
   * @generated
   */
  String getGeburtsDatum();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getGeburtsDatum <em>Geburts Datum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Geburts Datum</em>' attribute.
   * @see #getGeburtsDatum()
   * @generated
   */
  void setGeburtsDatum(String value);

  /**
   * Returns the value of the '<em><b>Todes Datum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Todes Datum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Todes Datum</em>' attribute.
   * @see #setTodesDatum(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_TodesDatum()
   * @model
   * @generated
   */
  String getTodesDatum();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getTodesDatum <em>Todes Datum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Todes Datum</em>' attribute.
   * @see #getTodesDatum()
   * @generated
   */
  void setTodesDatum(String value);

  /**
   * Returns the value of the '<em><b>Vater</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vater</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vater</em>' reference.
   * @see #setVater(Person)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Vater()
   * @model
   * @generated
   */
  Person getVater();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getVater <em>Vater</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vater</em>' reference.
   * @see #getVater()
   * @generated
   */
  void setVater(Person value);

  /**
   * Returns the value of the '<em><b>Mutter</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mutter</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mutter</em>' reference.
   * @see #setMutter(Person)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Mutter()
   * @model
   * @generated
   */
  Person getMutter();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getMutter <em>Mutter</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mutter</em>' reference.
   * @see #getMutter()
   * @generated
   */
  void setMutter(Person value);

  /**
   * Returns the value of the '<em><b>Kinder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kinder</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kinder</em>' containment reference.
   * @see #setKinder(Kinder)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Kinder()
   * @model containment="true"
   * @generated
   */
  Kinder getKinder();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getKinder <em>Kinder</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kinder</em>' containment reference.
   * @see #getKinder()
   * @generated
   */
  void setKinder(Kinder value);

  /**
   * Returns the value of the '<em><b>Stiefkinder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stiefkinder</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stiefkinder</em>' containment reference.
   * @see #setStiefkinder(Kinder)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Stiefkinder()
   * @model containment="true"
   * @generated
   */
  Kinder getStiefkinder();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Person#getStiefkinder <em>Stiefkinder</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stiefkinder</em>' containment reference.
   * @see #getStiefkinder()
   * @generated
   */
  void setStiefkinder(Kinder value);

  /**
   * Returns the value of the '<em><b>Beziehungen</b></em>' containment reference list.
   * The list contents are of type {@link com.github.funthomas424242.dsl.ahnen.Beziehung}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Beziehungen</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beziehungen</em>' containment reference list.
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Beziehungen()
   * @model containment="true"
   * @generated
   */
  EList<Beziehung> getBeziehungen();

  /**
   * Returns the value of the '<em><b>Ereignisse</b></em>' containment reference list.
   * The list contents are of type {@link com.github.funthomas424242.dsl.ahnen.Ereignis}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ereignisse</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ereignisse</em>' containment reference list.
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getPerson_Ereignisse()
   * @model containment="true"
   * @generated
   */
  EList<Ereignis> getEreignisse();

} // Person
