/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schulausbildung</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Schulausbildung#getAbschluss <em>Abschluss</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getSchulausbildung()
 * @model
 * @generated
 */
public interface Schulausbildung extends Ereignis
{
  /**
   * Returns the value of the '<em><b>Abschluss</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abschluss</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abschluss</em>' attribute.
   * @see #setAbschluss(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getSchulausbildung_Abschluss()
   * @model
   * @generated
   */
  String getAbschluss();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Schulausbildung#getAbschluss <em>Abschluss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abschluss</em>' attribute.
   * @see #getAbschluss()
   * @generated
   */
  void setAbschluss(String value);

} // Schulausbildung
