/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Taetigkeit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getBeruf <em>Beruf</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getArbeitgeber <em>Arbeitgeber</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getOrt <em>Ort</em>}</li>
 * </ul>
 *
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getTaetigkeit()
 * @model
 * @generated
 */
public interface Taetigkeit extends Ereignis
{
  /**
   * Returns the value of the '<em><b>Beruf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Beruf</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beruf</em>' attribute.
   * @see #setBeruf(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getTaetigkeit_Beruf()
   * @model
   * @generated
   */
  String getBeruf();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getBeruf <em>Beruf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Beruf</em>' attribute.
   * @see #getBeruf()
   * @generated
   */
  void setBeruf(String value);

  /**
   * Returns the value of the '<em><b>Arbeitgeber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arbeitgeber</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arbeitgeber</em>' attribute.
   * @see #setArbeitgeber(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getTaetigkeit_Arbeitgeber()
   * @model
   * @generated
   */
  String getArbeitgeber();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getArbeitgeber <em>Arbeitgeber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arbeitgeber</em>' attribute.
   * @see #getArbeitgeber()
   * @generated
   */
  void setArbeitgeber(String value);

  /**
   * Returns the value of the '<em><b>Ort</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ort</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ort</em>' attribute.
   * @see #setOrt(String)
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#getTaetigkeit_Ort()
   * @model
   * @generated
   */
  String getOrt();

  /**
   * Sets the value of the '{@link com.github.funthomas424242.dsl.ahnen.Taetigkeit#getOrt <em>Ort</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ort</em>' attribute.
   * @see #getOrt()
   * @generated
   */
  void setOrt(String value);

} // Taetigkeit
