/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen.impl;

import com.github.funthomas424242.dsl.ahnen.AhnenFactory;
import com.github.funthomas424242.dsl.ahnen.AhnenPackage;
import com.github.funthomas424242.dsl.ahnen.Autor;
import com.github.funthomas424242.dsl.ahnen.Beziehung;
import com.github.funthomas424242.dsl.ahnen.Dateiart;
import com.github.funthomas424242.dsl.ahnen.Ereignis;
import com.github.funthomas424242.dsl.ahnen.Familie;
import com.github.funthomas424242.dsl.ahnen.FamilienImport;
import com.github.funthomas424242.dsl.ahnen.Familienbuch;
import com.github.funthomas424242.dsl.ahnen.Geschlecht;
import com.github.funthomas424242.dsl.ahnen.Kinder;
import com.github.funthomas424242.dsl.ahnen.Model;
import com.github.funthomas424242.dsl.ahnen.Person;
import com.github.funthomas424242.dsl.ahnen.Schulausbildung;
import com.github.funthomas424242.dsl.ahnen.Taetigkeit;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AhnenPackageImpl extends EPackageImpl implements AhnenPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dateiartEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass familieEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass personEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ereignisEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass schulausbildungEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass taetigkeitEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass kinderEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass beziehungEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass familienbuchEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass familienImportEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass autorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum geschlechtEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private AhnenPackageImpl()
  {
    super(eNS_URI, AhnenFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link AhnenPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static AhnenPackage init()
  {
    if (isInited) return (AhnenPackage)EPackage.Registry.INSTANCE.getEPackage(AhnenPackage.eNS_URI);

    // Obtain or create and register package
    AhnenPackageImpl theAhnenPackage = (AhnenPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof AhnenPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new AhnenPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theAhnenPackage.createPackageContents();

    // Initialize created meta-data
    theAhnenPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theAhnenPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(AhnenPackage.eNS_URI, theAhnenPackage);
    return theAhnenPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Datei()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDateiart()
  {
    return dateiartEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDateiart_Buch()
  {
    return (EReference)dateiartEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDateiart_Familie()
  {
    return (EReference)dateiartEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFamilie()
  {
    return familieEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFamilie_Name()
  {
    return (EAttribute)familieEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFamilie_Personen()
  {
    return (EReference)familieEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPerson()
  {
    return personEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_Name()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_LetzteAenderung()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_Vorname()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_Mittelname()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_Nachname()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_Geburtsname()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_Rufname()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_Geschlecht()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_GeburtsDatum()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPerson_TodesDatum()
  {
    return (EAttribute)personEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPerson_Vater()
  {
    return (EReference)personEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPerson_Mutter()
  {
    return (EReference)personEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPerson_Kinder()
  {
    return (EReference)personEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPerson_Stiefkinder()
  {
    return (EReference)personEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPerson_Beziehungen()
  {
    return (EReference)personEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPerson_Ereignisse()
  {
    return (EReference)personEClass.getEStructuralFeatures().get(15);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEreignis()
  {
    return ereignisEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEreignis_Von()
  {
    return (EAttribute)ereignisEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEreignis_Bis()
  {
    return (EAttribute)ereignisEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSchulausbildung()
  {
    return schulausbildungEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSchulausbildung_Abschluss()
  {
    return (EAttribute)schulausbildungEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTaetigkeit()
  {
    return taetigkeitEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaetigkeit_Beruf()
  {
    return (EAttribute)taetigkeitEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaetigkeit_Arbeitgeber()
  {
    return (EAttribute)taetigkeitEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaetigkeit_Ort()
  {
    return (EAttribute)taetigkeitEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getKinder()
  {
    return kinderEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getKinder_Kind()
  {
    return (EReference)kinderEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getKinder_Next()
  {
    return (EReference)kinderEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBeziehung()
  {
    return beziehungEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBeziehung_Beziehung()
  {
    return (EReference)beziehungEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBeziehung_VonDatum()
  {
    return (EAttribute)beziehungEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBeziehung_BisDatum()
  {
    return (EAttribute)beziehungEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBeziehung_Hochzeitstag()
  {
    return (EAttribute)beziehungEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBeziehung_Scheidungstag()
  {
    return (EAttribute)beziehungEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFamilienbuch()
  {
    return familienbuchEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFamilienbuch_Name()
  {
    return (EAttribute)familienbuchEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFamilienbuch_Familie()
  {
    return (EAttribute)familienbuchEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFamilienbuch_Person()
  {
    return (EReference)familienbuchEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFamilienbuch_Version()
  {
    return (EAttribute)familienbuchEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFamilienbuch_Titel()
  {
    return (EAttribute)familienbuchEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFamilienbuch_Vorwort()
  {
    return (EAttribute)familienbuchEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFamilienbuch_Autor()
  {
    return (EReference)familienbuchEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFamilienbuch_Familien()
  {
    return (EReference)familienbuchEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFamilienImport()
  {
    return familienImportEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFamilienImport_Familie()
  {
    return (EReference)familienImportEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAutor()
  {
    return autorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAutor_Vorname()
  {
    return (EAttribute)autorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAutor_Nachname()
  {
    return (EAttribute)autorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAutor_OrganisationsName()
  {
    return (EAttribute)autorEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getGeschlecht()
  {
    return geschlechtEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AhnenFactory getAhnenFactory()
  {
    return (AhnenFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__DATEI);

    dateiartEClass = createEClass(DATEIART);
    createEReference(dateiartEClass, DATEIART__BUCH);
    createEReference(dateiartEClass, DATEIART__FAMILIE);

    familieEClass = createEClass(FAMILIE);
    createEAttribute(familieEClass, FAMILIE__NAME);
    createEReference(familieEClass, FAMILIE__PERSONEN);

    personEClass = createEClass(PERSON);
    createEAttribute(personEClass, PERSON__NAME);
    createEAttribute(personEClass, PERSON__LETZTE_AENDERUNG);
    createEAttribute(personEClass, PERSON__VORNAME);
    createEAttribute(personEClass, PERSON__MITTELNAME);
    createEAttribute(personEClass, PERSON__NACHNAME);
    createEAttribute(personEClass, PERSON__GEBURTSNAME);
    createEAttribute(personEClass, PERSON__RUFNAME);
    createEAttribute(personEClass, PERSON__GESCHLECHT);
    createEAttribute(personEClass, PERSON__GEBURTS_DATUM);
    createEAttribute(personEClass, PERSON__TODES_DATUM);
    createEReference(personEClass, PERSON__VATER);
    createEReference(personEClass, PERSON__MUTTER);
    createEReference(personEClass, PERSON__KINDER);
    createEReference(personEClass, PERSON__STIEFKINDER);
    createEReference(personEClass, PERSON__BEZIEHUNGEN);
    createEReference(personEClass, PERSON__EREIGNISSE);

    ereignisEClass = createEClass(EREIGNIS);
    createEAttribute(ereignisEClass, EREIGNIS__VON);
    createEAttribute(ereignisEClass, EREIGNIS__BIS);

    schulausbildungEClass = createEClass(SCHULAUSBILDUNG);
    createEAttribute(schulausbildungEClass, SCHULAUSBILDUNG__ABSCHLUSS);

    taetigkeitEClass = createEClass(TAETIGKEIT);
    createEAttribute(taetigkeitEClass, TAETIGKEIT__BERUF);
    createEAttribute(taetigkeitEClass, TAETIGKEIT__ARBEITGEBER);
    createEAttribute(taetigkeitEClass, TAETIGKEIT__ORT);

    kinderEClass = createEClass(KINDER);
    createEReference(kinderEClass, KINDER__KIND);
    createEReference(kinderEClass, KINDER__NEXT);

    beziehungEClass = createEClass(BEZIEHUNG);
    createEReference(beziehungEClass, BEZIEHUNG__BEZIEHUNG);
    createEAttribute(beziehungEClass, BEZIEHUNG__VON_DATUM);
    createEAttribute(beziehungEClass, BEZIEHUNG__BIS_DATUM);
    createEAttribute(beziehungEClass, BEZIEHUNG__HOCHZEITSTAG);
    createEAttribute(beziehungEClass, BEZIEHUNG__SCHEIDUNGSTAG);

    familienbuchEClass = createEClass(FAMILIENBUCH);
    createEAttribute(familienbuchEClass, FAMILIENBUCH__NAME);
    createEAttribute(familienbuchEClass, FAMILIENBUCH__FAMILIE);
    createEReference(familienbuchEClass, FAMILIENBUCH__PERSON);
    createEAttribute(familienbuchEClass, FAMILIENBUCH__VERSION);
    createEAttribute(familienbuchEClass, FAMILIENBUCH__TITEL);
    createEAttribute(familienbuchEClass, FAMILIENBUCH__VORWORT);
    createEReference(familienbuchEClass, FAMILIENBUCH__AUTOR);
    createEReference(familienbuchEClass, FAMILIENBUCH__FAMILIEN);

    familienImportEClass = createEClass(FAMILIEN_IMPORT);
    createEReference(familienImportEClass, FAMILIEN_IMPORT__FAMILIE);

    autorEClass = createEClass(AUTOR);
    createEAttribute(autorEClass, AUTOR__VORNAME);
    createEAttribute(autorEClass, AUTOR__NACHNAME);
    createEAttribute(autorEClass, AUTOR__ORGANISATIONS_NAME);

    // Create enums
    geschlechtEEnum = createEEnum(GESCHLECHT);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    schulausbildungEClass.getESuperTypes().add(this.getEreignis());
    taetigkeitEClass.getESuperTypes().add(this.getEreignis());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Datei(), this.getDateiart(), null, "datei", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dateiartEClass, Dateiart.class, "Dateiart", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDateiart_Buch(), this.getFamilienbuch(), null, "buch", null, 0, 1, Dateiart.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDateiart_Familie(), this.getFamilie(), null, "familie", null, 0, 1, Dateiart.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(familieEClass, Familie.class, "Familie", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFamilie_Name(), ecorePackage.getEString(), "name", null, 0, 1, Familie.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFamilie_Personen(), this.getPerson(), null, "personen", null, 0, -1, Familie.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(personEClass, Person.class, "Person", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPerson_Name(), ecorePackage.getEString(), "name", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_LetzteAenderung(), ecorePackage.getEString(), "letzteAenderung", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_Vorname(), ecorePackage.getEString(), "vorname", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_Mittelname(), ecorePackage.getEString(), "mittelname", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_Nachname(), ecorePackage.getEString(), "nachname", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_Geburtsname(), ecorePackage.getEString(), "geburtsname", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_Rufname(), ecorePackage.getEString(), "rufname", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_Geschlecht(), this.getGeschlecht(), "geschlecht", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_GeburtsDatum(), ecorePackage.getEString(), "geburtsDatum", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPerson_TodesDatum(), ecorePackage.getEString(), "todesDatum", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPerson_Vater(), this.getPerson(), null, "vater", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPerson_Mutter(), this.getPerson(), null, "mutter", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPerson_Kinder(), this.getKinder(), null, "kinder", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPerson_Stiefkinder(), this.getKinder(), null, "stiefkinder", null, 0, 1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPerson_Beziehungen(), this.getBeziehung(), null, "beziehungen", null, 0, -1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPerson_Ereignisse(), this.getEreignis(), null, "ereignisse", null, 0, -1, Person.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ereignisEClass, Ereignis.class, "Ereignis", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEreignis_Von(), ecorePackage.getEString(), "von", null, 0, 1, Ereignis.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEreignis_Bis(), ecorePackage.getEString(), "bis", null, 0, 1, Ereignis.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(schulausbildungEClass, Schulausbildung.class, "Schulausbildung", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSchulausbildung_Abschluss(), ecorePackage.getEString(), "abschluss", null, 0, 1, Schulausbildung.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(taetigkeitEClass, Taetigkeit.class, "Taetigkeit", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTaetigkeit_Beruf(), ecorePackage.getEString(), "beruf", null, 0, 1, Taetigkeit.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTaetigkeit_Arbeitgeber(), ecorePackage.getEString(), "arbeitgeber", null, 0, 1, Taetigkeit.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTaetigkeit_Ort(), ecorePackage.getEString(), "ort", null, 0, 1, Taetigkeit.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(kinderEClass, Kinder.class, "Kinder", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getKinder_Kind(), this.getPerson(), null, "kind", null, 0, 1, Kinder.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getKinder_Next(), this.getKinder(), null, "next", null, 0, 1, Kinder.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(beziehungEClass, Beziehung.class, "Beziehung", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBeziehung_Beziehung(), this.getPerson(), null, "beziehung", null, 0, 1, Beziehung.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBeziehung_VonDatum(), ecorePackage.getEString(), "vonDatum", null, 0, 1, Beziehung.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBeziehung_BisDatum(), ecorePackage.getEString(), "bisDatum", null, 0, 1, Beziehung.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBeziehung_Hochzeitstag(), ecorePackage.getEString(), "hochzeitstag", null, 0, 1, Beziehung.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBeziehung_Scheidungstag(), ecorePackage.getEString(), "scheidungstag", null, 0, 1, Beziehung.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(familienbuchEClass, Familienbuch.class, "Familienbuch", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFamilienbuch_Name(), ecorePackage.getEString(), "name", null, 0, 1, Familienbuch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFamilienbuch_Familie(), ecorePackage.getEString(), "familie", null, 0, 1, Familienbuch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFamilienbuch_Person(), this.getPerson(), null, "person", null, 0, 1, Familienbuch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFamilienbuch_Version(), ecorePackage.getEString(), "version", null, 0, 1, Familienbuch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFamilienbuch_Titel(), ecorePackage.getEString(), "titel", null, 0, 1, Familienbuch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFamilienbuch_Vorwort(), ecorePackage.getEString(), "vorwort", null, 0, 1, Familienbuch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFamilienbuch_Autor(), this.getAutor(), null, "autor", null, 0, 1, Familienbuch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFamilienbuch_Familien(), this.getFamilienImport(), null, "familien", null, 0, -1, Familienbuch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(familienImportEClass, FamilienImport.class, "FamilienImport", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFamilienImport_Familie(), this.getFamilie(), null, "familie", null, 0, 1, FamilienImport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(autorEClass, Autor.class, "Autor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAutor_Vorname(), ecorePackage.getEString(), "vorname", null, 0, 1, Autor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAutor_Nachname(), ecorePackage.getEString(), "nachname", null, 0, 1, Autor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAutor_OrganisationsName(), ecorePackage.getEString(), "organisationsName", null, 0, 1, Autor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(geschlechtEEnum, Geschlecht.class, "Geschlecht");
    addEEnumLiteral(geschlechtEEnum, Geschlecht.UNBEKANNT);
    addEEnumLiteral(geschlechtEEnum, Geschlecht.MAENNLICH);
    addEEnumLiteral(geschlechtEEnum, Geschlecht.WEIBLICH);

    // Create resource
    createResource(eNS_URI);
  }

} //AhnenPackageImpl
