/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen.impl;

import com.github.funthomas424242.dsl.ahnen.AhnenPackage;
import com.github.funthomas424242.dsl.ahnen.Dateiart;
import com.github.funthomas424242.dsl.ahnen.Familie;
import com.github.funthomas424242.dsl.ahnen.Familienbuch;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dateiart</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.DateiartImpl#getBuch <em>Buch</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.DateiartImpl#getFamilie <em>Familie</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DateiartImpl extends MinimalEObjectImpl.Container implements Dateiart
{
  /**
   * The cached value of the '{@link #getBuch() <em>Buch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBuch()
   * @generated
   * @ordered
   */
  protected Familienbuch buch;

  /**
   * The cached value of the '{@link #getFamilie() <em>Familie</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFamilie()
   * @generated
   * @ordered
   */
  protected Familie familie;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DateiartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AhnenPackage.Literals.DATEIART;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Familienbuch getBuch()
  {
    return buch;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBuch(Familienbuch newBuch, NotificationChain msgs)
  {
    Familienbuch oldBuch = buch;
    buch = newBuch;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AhnenPackage.DATEIART__BUCH, oldBuch, newBuch);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBuch(Familienbuch newBuch)
  {
    if (newBuch != buch)
    {
      NotificationChain msgs = null;
      if (buch != null)
        msgs = ((InternalEObject)buch).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AhnenPackage.DATEIART__BUCH, null, msgs);
      if (newBuch != null)
        msgs = ((InternalEObject)newBuch).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AhnenPackage.DATEIART__BUCH, null, msgs);
      msgs = basicSetBuch(newBuch, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.DATEIART__BUCH, newBuch, newBuch));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Familie getFamilie()
  {
    return familie;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFamilie(Familie newFamilie, NotificationChain msgs)
  {
    Familie oldFamilie = familie;
    familie = newFamilie;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AhnenPackage.DATEIART__FAMILIE, oldFamilie, newFamilie);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFamilie(Familie newFamilie)
  {
    if (newFamilie != familie)
    {
      NotificationChain msgs = null;
      if (familie != null)
        msgs = ((InternalEObject)familie).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AhnenPackage.DATEIART__FAMILIE, null, msgs);
      if (newFamilie != null)
        msgs = ((InternalEObject)newFamilie).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AhnenPackage.DATEIART__FAMILIE, null, msgs);
      msgs = basicSetFamilie(newFamilie, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.DATEIART__FAMILIE, newFamilie, newFamilie));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AhnenPackage.DATEIART__BUCH:
        return basicSetBuch(null, msgs);
      case AhnenPackage.DATEIART__FAMILIE:
        return basicSetFamilie(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AhnenPackage.DATEIART__BUCH:
        return getBuch();
      case AhnenPackage.DATEIART__FAMILIE:
        return getFamilie();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AhnenPackage.DATEIART__BUCH:
        setBuch((Familienbuch)newValue);
        return;
      case AhnenPackage.DATEIART__FAMILIE:
        setFamilie((Familie)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AhnenPackage.DATEIART__BUCH:
        setBuch((Familienbuch)null);
        return;
      case AhnenPackage.DATEIART__FAMILIE:
        setFamilie((Familie)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AhnenPackage.DATEIART__BUCH:
        return buch != null;
      case AhnenPackage.DATEIART__FAMILIE:
        return familie != null;
    }
    return super.eIsSet(featureID);
  }

} //DateiartImpl
