/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen.impl;

import com.github.funthomas424242.dsl.ahnen.AhnenPackage;
import com.github.funthomas424242.dsl.ahnen.Familie;
import com.github.funthomas424242.dsl.ahnen.FamilienImport;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Familien Import</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienImportImpl#getFamilie <em>Familie</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FamilienImportImpl extends MinimalEObjectImpl.Container implements FamilienImport
{
  /**
   * The cached value of the '{@link #getFamilie() <em>Familie</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFamilie()
   * @generated
   * @ordered
   */
  protected Familie familie;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FamilienImportImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AhnenPackage.Literals.FAMILIEN_IMPORT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Familie getFamilie()
  {
    if (familie != null && familie.eIsProxy())
    {
      InternalEObject oldFamilie = (InternalEObject)familie;
      familie = (Familie)eResolveProxy(oldFamilie);
      if (familie != oldFamilie)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AhnenPackage.FAMILIEN_IMPORT__FAMILIE, oldFamilie, familie));
      }
    }
    return familie;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Familie basicGetFamilie()
  {
    return familie;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFamilie(Familie newFamilie)
  {
    Familie oldFamilie = familie;
    familie = newFamilie;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIEN_IMPORT__FAMILIE, oldFamilie, familie));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIEN_IMPORT__FAMILIE:
        if (resolve) return getFamilie();
        return basicGetFamilie();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIEN_IMPORT__FAMILIE:
        setFamilie((Familie)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIEN_IMPORT__FAMILIE:
        setFamilie((Familie)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIEN_IMPORT__FAMILIE:
        return familie != null;
    }
    return super.eIsSet(featureID);
  }

} //FamilienImportImpl
