/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen.impl;

import com.github.funthomas424242.dsl.ahnen.AhnenPackage;
import com.github.funthomas424242.dsl.ahnen.Autor;
import com.github.funthomas424242.dsl.ahnen.FamilienImport;
import com.github.funthomas424242.dsl.ahnen.Familienbuch;
import com.github.funthomas424242.dsl.ahnen.Person;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Familienbuch</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl#getFamilie <em>Familie</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl#getPerson <em>Person</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl#getVersion <em>Version</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl#getTitel <em>Titel</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl#getVorwort <em>Vorwort</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl#getAutor <em>Autor</em>}</li>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.FamilienbuchImpl#getFamilien <em>Familien</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FamilienbuchImpl extends MinimalEObjectImpl.Container implements Familienbuch
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getFamilie() <em>Familie</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFamilie()
   * @generated
   * @ordered
   */
  protected static final String FAMILIE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFamilie() <em>Familie</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFamilie()
   * @generated
   * @ordered
   */
  protected String familie = FAMILIE_EDEFAULT;

  /**
   * The cached value of the '{@link #getPerson() <em>Person</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPerson()
   * @generated
   * @ordered
   */
  protected Person person;

  /**
   * The default value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected static final String VERSION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected String version = VERSION_EDEFAULT;

  /**
   * The default value of the '{@link #getTitel() <em>Titel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitel()
   * @generated
   * @ordered
   */
  protected static final String TITEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitel() <em>Titel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitel()
   * @generated
   * @ordered
   */
  protected String titel = TITEL_EDEFAULT;

  /**
   * The default value of the '{@link #getVorwort() <em>Vorwort</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVorwort()
   * @generated
   * @ordered
   */
  protected static final String VORWORT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVorwort() <em>Vorwort</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVorwort()
   * @generated
   * @ordered
   */
  protected String vorwort = VORWORT_EDEFAULT;

  /**
   * The cached value of the '{@link #getAutor() <em>Autor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAutor()
   * @generated
   * @ordered
   */
  protected Autor autor;

  /**
   * The cached value of the '{@link #getFamilien() <em>Familien</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFamilien()
   * @generated
   * @ordered
   */
  protected EList<FamilienImport> familien;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FamilienbuchImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AhnenPackage.Literals.FAMILIENBUCH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIENBUCH__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFamilie()
  {
    return familie;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFamilie(String newFamilie)
  {
    String oldFamilie = familie;
    familie = newFamilie;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIENBUCH__FAMILIE, oldFamilie, familie));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Person getPerson()
  {
    if (person != null && person.eIsProxy())
    {
      InternalEObject oldPerson = (InternalEObject)person;
      person = (Person)eResolveProxy(oldPerson);
      if (person != oldPerson)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AhnenPackage.FAMILIENBUCH__PERSON, oldPerson, person));
      }
    }
    return person;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Person basicGetPerson()
  {
    return person;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPerson(Person newPerson)
  {
    Person oldPerson = person;
    person = newPerson;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIENBUCH__PERSON, oldPerson, person));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVersion()
  {
    return version;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVersion(String newVersion)
  {
    String oldVersion = version;
    version = newVersion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIENBUCH__VERSION, oldVersion, version));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTitel()
  {
    return titel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTitel(String newTitel)
  {
    String oldTitel = titel;
    titel = newTitel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIENBUCH__TITEL, oldTitel, titel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVorwort()
  {
    return vorwort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVorwort(String newVorwort)
  {
    String oldVorwort = vorwort;
    vorwort = newVorwort;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIENBUCH__VORWORT, oldVorwort, vorwort));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Autor getAutor()
  {
    return autor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAutor(Autor newAutor, NotificationChain msgs)
  {
    Autor oldAutor = autor;
    autor = newAutor;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIENBUCH__AUTOR, oldAutor, newAutor);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAutor(Autor newAutor)
  {
    if (newAutor != autor)
    {
      NotificationChain msgs = null;
      if (autor != null)
        msgs = ((InternalEObject)autor).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AhnenPackage.FAMILIENBUCH__AUTOR, null, msgs);
      if (newAutor != null)
        msgs = ((InternalEObject)newAutor).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AhnenPackage.FAMILIENBUCH__AUTOR, null, msgs);
      msgs = basicSetAutor(newAutor, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.FAMILIENBUCH__AUTOR, newAutor, newAutor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<FamilienImport> getFamilien()
  {
    if (familien == null)
    {
      familien = new EObjectContainmentEList<FamilienImport>(FamilienImport.class, this, AhnenPackage.FAMILIENBUCH__FAMILIEN);
    }
    return familien;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIENBUCH__AUTOR:
        return basicSetAutor(null, msgs);
      case AhnenPackage.FAMILIENBUCH__FAMILIEN:
        return ((InternalEList<?>)getFamilien()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIENBUCH__NAME:
        return getName();
      case AhnenPackage.FAMILIENBUCH__FAMILIE:
        return getFamilie();
      case AhnenPackage.FAMILIENBUCH__PERSON:
        if (resolve) return getPerson();
        return basicGetPerson();
      case AhnenPackage.FAMILIENBUCH__VERSION:
        return getVersion();
      case AhnenPackage.FAMILIENBUCH__TITEL:
        return getTitel();
      case AhnenPackage.FAMILIENBUCH__VORWORT:
        return getVorwort();
      case AhnenPackage.FAMILIENBUCH__AUTOR:
        return getAutor();
      case AhnenPackage.FAMILIENBUCH__FAMILIEN:
        return getFamilien();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIENBUCH__NAME:
        setName((String)newValue);
        return;
      case AhnenPackage.FAMILIENBUCH__FAMILIE:
        setFamilie((String)newValue);
        return;
      case AhnenPackage.FAMILIENBUCH__PERSON:
        setPerson((Person)newValue);
        return;
      case AhnenPackage.FAMILIENBUCH__VERSION:
        setVersion((String)newValue);
        return;
      case AhnenPackage.FAMILIENBUCH__TITEL:
        setTitel((String)newValue);
        return;
      case AhnenPackage.FAMILIENBUCH__VORWORT:
        setVorwort((String)newValue);
        return;
      case AhnenPackage.FAMILIENBUCH__AUTOR:
        setAutor((Autor)newValue);
        return;
      case AhnenPackage.FAMILIENBUCH__FAMILIEN:
        getFamilien().clear();
        getFamilien().addAll((Collection<? extends FamilienImport>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIENBUCH__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AhnenPackage.FAMILIENBUCH__FAMILIE:
        setFamilie(FAMILIE_EDEFAULT);
        return;
      case AhnenPackage.FAMILIENBUCH__PERSON:
        setPerson((Person)null);
        return;
      case AhnenPackage.FAMILIENBUCH__VERSION:
        setVersion(VERSION_EDEFAULT);
        return;
      case AhnenPackage.FAMILIENBUCH__TITEL:
        setTitel(TITEL_EDEFAULT);
        return;
      case AhnenPackage.FAMILIENBUCH__VORWORT:
        setVorwort(VORWORT_EDEFAULT);
        return;
      case AhnenPackage.FAMILIENBUCH__AUTOR:
        setAutor((Autor)null);
        return;
      case AhnenPackage.FAMILIENBUCH__FAMILIEN:
        getFamilien().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AhnenPackage.FAMILIENBUCH__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AhnenPackage.FAMILIENBUCH__FAMILIE:
        return FAMILIE_EDEFAULT == null ? familie != null : !FAMILIE_EDEFAULT.equals(familie);
      case AhnenPackage.FAMILIENBUCH__PERSON:
        return person != null;
      case AhnenPackage.FAMILIENBUCH__VERSION:
        return VERSION_EDEFAULT == null ? version != null : !VERSION_EDEFAULT.equals(version);
      case AhnenPackage.FAMILIENBUCH__TITEL:
        return TITEL_EDEFAULT == null ? titel != null : !TITEL_EDEFAULT.equals(titel);
      case AhnenPackage.FAMILIENBUCH__VORWORT:
        return VORWORT_EDEFAULT == null ? vorwort != null : !VORWORT_EDEFAULT.equals(vorwort);
      case AhnenPackage.FAMILIENBUCH__AUTOR:
        return autor != null;
      case AhnenPackage.FAMILIENBUCH__FAMILIEN:
        return familien != null && !familien.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", familie: ");
    result.append(familie);
    result.append(", version: ");
    result.append(version);
    result.append(", titel: ");
    result.append(titel);
    result.append(", vorwort: ");
    result.append(vorwort);
    result.append(')');
    return result.toString();
  }

} //FamilienbuchImpl
