/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen.impl;

import com.github.funthomas424242.dsl.ahnen.AhnenPackage;
import com.github.funthomas424242.dsl.ahnen.Schulausbildung;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Schulausbildung</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.github.funthomas424242.dsl.ahnen.impl.SchulausbildungImpl#getAbschluss <em>Abschluss</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SchulausbildungImpl extends EreignisImpl implements Schulausbildung
{
  /**
   * The default value of the '{@link #getAbschluss() <em>Abschluss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbschluss()
   * @generated
   * @ordered
   */
  protected static final String ABSCHLUSS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAbschluss() <em>Abschluss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbschluss()
   * @generated
   * @ordered
   */
  protected String abschluss = ABSCHLUSS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SchulausbildungImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AhnenPackage.Literals.SCHULAUSBILDUNG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAbschluss()
  {
    return abschluss;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAbschluss(String newAbschluss)
  {
    String oldAbschluss = abschluss;
    abschluss = newAbschluss;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AhnenPackage.SCHULAUSBILDUNG__ABSCHLUSS, oldAbschluss, abschluss));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AhnenPackage.SCHULAUSBILDUNG__ABSCHLUSS:
        return getAbschluss();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AhnenPackage.SCHULAUSBILDUNG__ABSCHLUSS:
        setAbschluss((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AhnenPackage.SCHULAUSBILDUNG__ABSCHLUSS:
        setAbschluss(ABSCHLUSS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AhnenPackage.SCHULAUSBILDUNG__ABSCHLUSS:
        return ABSCHLUSS_EDEFAULT == null ? abschluss != null : !ABSCHLUSS_EDEFAULT.equals(abschluss);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (abschluss: ");
    result.append(abschluss);
    result.append(')');
    return result.toString();
  }

} //SchulausbildungImpl
