/*
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAhnenValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.github.funthomas424242.dsl.ahnen.AhnenPackage.eINSTANCE);
		return result;
	}
	
}
