/*
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AhnenAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/github/funthomas424242/dsl/parser/antlr/internal/InternalAhnen.tokens");
	}
}
