/*
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class AhnenGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Model");
		private final Assignment cDateiAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDateiDateiartParserRuleCall_0 = (RuleCall)cDateiAssignment.eContents().get(0);
		
		//Model:
		//	datei=Dateiart;
		@Override public ParserRule getRule() { return rule; }
		
		//datei=Dateiart
		public Assignment getDateiAssignment() { return cDateiAssignment; }
		
		//Dateiart
		public RuleCall getDateiDateiartParserRuleCall_0() { return cDateiDateiartParserRuleCall_0; }
	}
	public class DateiartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Dateiart");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cBuchAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cBuchFamilienbuchParserRuleCall_0_0 = (RuleCall)cBuchAssignment_0.eContents().get(0);
		private final Assignment cFamilieAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cFamilieFamilieParserRuleCall_1_0 = (RuleCall)cFamilieAssignment_1.eContents().get(0);
		
		//Dateiart:
		//	buch=Familienbuch | familie=Familie;
		@Override public ParserRule getRule() { return rule; }
		
		//buch=Familienbuch | familie=Familie
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//buch=Familienbuch
		public Assignment getBuchAssignment_0() { return cBuchAssignment_0; }
		
		//Familienbuch
		public RuleCall getBuchFamilienbuchParserRuleCall_0_0() { return cBuchFamilienbuchParserRuleCall_0_0; }
		
		//familie=Familie
		public Assignment getFamilieAssignment_1() { return cFamilieAssignment_1; }
		
		//Familie
		public RuleCall getFamilieFamilieParserRuleCall_1_0() { return cFamilieFamilieParserRuleCall_1_0; }
	}
	public class FamilieElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Familie");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFamilieAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFamilieKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPersonenAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPersonenPersonParserRuleCall_4_0 = (RuleCall)cPersonenAssignment_4.eContents().get(0);
		
		//Familie:
		//	{Familie}
		//	"Familie" name=ID ";"
		//	personen+=Person+;
		@Override public ParserRule getRule() { return rule; }
		
		//{Familie} "Familie" name=ID ";" personen+=Person+
		public Group getGroup() { return cGroup; }
		
		//{Familie}
		public Action getFamilieAction_0() { return cFamilieAction_0; }
		
		//"Familie"
		public Keyword getFamilieKeyword_1() { return cFamilieKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
		
		//personen+=Person+
		public Assignment getPersonenAssignment_4() { return cPersonenAssignment_4; }
		
		//Person
		public RuleCall getPersonenPersonParserRuleCall_4_0() { return cPersonenPersonParserRuleCall_4_0; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Person");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPersonAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPersonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLetzteKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cÄnderungKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLetzteAenderungAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLetzteAenderungDATUMParserRuleCall_6_0 = (RuleCall)cLetzteAenderungAssignment_6.eContents().get(0);
		private final Keyword cFullStopKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cVornameKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Alternatives cAlternatives_9 = (Alternatives)cGroup.eContents().get(9);
		private final Assignment cVornameAssignment_9_0 = (Assignment)cAlternatives_9.eContents().get(0);
		private final RuleCall cVornameSTRINGTerminalRuleCall_9_0_0 = (RuleCall)cVornameAssignment_9_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_9_1 = (Keyword)cAlternatives_9.eContents().get(1);
		private final Keyword cFullStopKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cMittelnameKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Alternatives cAlternatives_12 = (Alternatives)cGroup.eContents().get(12);
		private final Assignment cMittelnameAssignment_12_0 = (Assignment)cAlternatives_12.eContents().get(0);
		private final RuleCall cMittelnameSTRINGTerminalRuleCall_12_0_0 = (RuleCall)cMittelnameAssignment_12_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_12_1 = (Keyword)cAlternatives_12.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_12_2 = (Keyword)cAlternatives_12.eContents().get(2);
		private final Keyword cFullStopKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cNachnameKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Alternatives cAlternatives_15 = (Alternatives)cGroup.eContents().get(15);
		private final Assignment cNachnameAssignment_15_0 = (Assignment)cAlternatives_15.eContents().get(0);
		private final RuleCall cNachnameSTRINGTerminalRuleCall_15_0_0 = (RuleCall)cNachnameAssignment_15_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_15_1 = (Keyword)cAlternatives_15.eContents().get(1);
		private final Keyword cFullStopKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cGeburtsnameKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Alternatives cAlternatives_18 = (Alternatives)cGroup.eContents().get(18);
		private final Assignment cGeburtsnameAssignment_18_0 = (Assignment)cAlternatives_18.eContents().get(0);
		private final RuleCall cGeburtsnameSTRINGTerminalRuleCall_18_0_0 = (RuleCall)cGeburtsnameAssignment_18_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_18_1 = (Keyword)cAlternatives_18.eContents().get(1);
		private final Keyword cFullStopKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cRufnameKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Alternatives cAlternatives_21 = (Alternatives)cGroup.eContents().get(21);
		private final Assignment cRufnameAssignment_21_0 = (Assignment)cAlternatives_21.eContents().get(0);
		private final RuleCall cRufnameSTRINGTerminalRuleCall_21_0_0 = (RuleCall)cRufnameAssignment_21_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_21_1 = (Keyword)cAlternatives_21.eContents().get(1);
		private final Keyword cFullStopKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Keyword cGeschlechtKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Assignment cGeschlechtAssignment_24 = (Assignment)cGroup.eContents().get(24);
		private final RuleCall cGeschlechtGeschlechtEnumRuleCall_24_0 = (RuleCall)cGeschlechtAssignment_24.eContents().get(0);
		private final Keyword cFullStopKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Keyword cGeburtsdatumKeyword_26 = (Keyword)cGroup.eContents().get(26);
		private final Alternatives cAlternatives_27 = (Alternatives)cGroup.eContents().get(27);
		private final Assignment cGeburtsDatumAssignment_27_0 = (Assignment)cAlternatives_27.eContents().get(0);
		private final RuleCall cGeburtsDatumDATUMParserRuleCall_27_0_0 = (RuleCall)cGeburtsDatumAssignment_27_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_27_1 = (Keyword)cAlternatives_27.eContents().get(1);
		private final Keyword cFullStopKeyword_28 = (Keyword)cGroup.eContents().get(28);
		private final Keyword cTodesdatumKeyword_29 = (Keyword)cGroup.eContents().get(29);
		private final Alternatives cAlternatives_30 = (Alternatives)cGroup.eContents().get(30);
		private final Assignment cTodesDatumAssignment_30_0 = (Assignment)cAlternatives_30.eContents().get(0);
		private final RuleCall cTodesDatumDATUMParserRuleCall_30_0_0 = (RuleCall)cTodesDatumAssignment_30_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_30_1 = (Keyword)cAlternatives_30.eContents().get(1);
		private final Keyword cLebendKeyword_30_2 = (Keyword)cAlternatives_30.eContents().get(2);
		private final Keyword cVermisstKeyword_30_3 = (Keyword)cAlternatives_30.eContents().get(3);
		private final Keyword cFullStopKeyword_31 = (Keyword)cGroup.eContents().get(31);
		private final Keyword cVaterKeyword_32 = (Keyword)cGroup.eContents().get(32);
		private final Alternatives cAlternatives_33 = (Alternatives)cGroup.eContents().get(33);
		private final Assignment cVaterAssignment_33_0 = (Assignment)cAlternatives_33.eContents().get(0);
		private final CrossReference cVaterPersonCrossReference_33_0_0 = (CrossReference)cVaterAssignment_33_0.eContents().get(0);
		private final RuleCall cVaterPersonSTRINGTerminalRuleCall_33_0_0_1 = (RuleCall)cVaterPersonCrossReference_33_0_0.eContents().get(1);
		private final Keyword cUnbekanntKeyword_33_1 = (Keyword)cAlternatives_33.eContents().get(1);
		private final Keyword cUnerfasstKeyword_33_2 = (Keyword)cAlternatives_33.eContents().get(2);
		private final Keyword cFullStopKeyword_34 = (Keyword)cGroup.eContents().get(34);
		private final Keyword cMutterKeyword_35 = (Keyword)cGroup.eContents().get(35);
		private final Alternatives cAlternatives_36 = (Alternatives)cGroup.eContents().get(36);
		private final Assignment cMutterAssignment_36_0 = (Assignment)cAlternatives_36.eContents().get(0);
		private final CrossReference cMutterPersonCrossReference_36_0_0 = (CrossReference)cMutterAssignment_36_0.eContents().get(0);
		private final RuleCall cMutterPersonSTRINGTerminalRuleCall_36_0_0_1 = (RuleCall)cMutterPersonCrossReference_36_0_0.eContents().get(1);
		private final Keyword cUnbekanntKeyword_36_1 = (Keyword)cAlternatives_36.eContents().get(1);
		private final Keyword cUnerfasstKeyword_36_2 = (Keyword)cAlternatives_36.eContents().get(2);
		private final Keyword cFullStopKeyword_37 = (Keyword)cGroup.eContents().get(37);
		private final Keyword cKinderKeyword_38 = (Keyword)cGroup.eContents().get(38);
		private final Alternatives cAlternatives_39 = (Alternatives)cGroup.eContents().get(39);
		private final Assignment cKinderAssignment_39_0 = (Assignment)cAlternatives_39.eContents().get(0);
		private final RuleCall cKinderKinderParserRuleCall_39_0_0 = (RuleCall)cKinderAssignment_39_0.eContents().get(0);
		private final Keyword cKeineKeyword_39_1 = (Keyword)cAlternatives_39.eContents().get(1);
		private final Keyword cFullStopKeyword_40 = (Keyword)cGroup.eContents().get(40);
		private final Keyword cStiefkinderKeyword_41 = (Keyword)cGroup.eContents().get(41);
		private final Alternatives cAlternatives_42 = (Alternatives)cGroup.eContents().get(42);
		private final Assignment cStiefkinderAssignment_42_0 = (Assignment)cAlternatives_42.eContents().get(0);
		private final RuleCall cStiefkinderKinderParserRuleCall_42_0_0 = (RuleCall)cStiefkinderAssignment_42_0.eContents().get(0);
		private final Keyword cKeineKeyword_42_1 = (Keyword)cAlternatives_42.eContents().get(1);
		private final Keyword cFullStopKeyword_43 = (Keyword)cGroup.eContents().get(43);
		private final Keyword cBeziehungenKeyword_44 = (Keyword)cGroup.eContents().get(44);
		private final Keyword cLeftCurlyBracketKeyword_45 = (Keyword)cGroup.eContents().get(45);
		private final Alternatives cAlternatives_46 = (Alternatives)cGroup.eContents().get(46);
		private final Assignment cBeziehungenAssignment_46_0 = (Assignment)cAlternatives_46.eContents().get(0);
		private final RuleCall cBeziehungenBeziehungParserRuleCall_46_0_0 = (RuleCall)cBeziehungenAssignment_46_0.eContents().get(0);
		private final Keyword cKeineKeyword_46_1 = (Keyword)cAlternatives_46.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_47 = (Keyword)cGroup.eContents().get(47);
		private final Keyword cEreignisseKeyword_48 = (Keyword)cGroup.eContents().get(48);
		private final Keyword cLeftCurlyBracketKeyword_49 = (Keyword)cGroup.eContents().get(49);
		private final Alternatives cAlternatives_50 = (Alternatives)cGroup.eContents().get(50);
		private final Assignment cEreignisseAssignment_50_0 = (Assignment)cAlternatives_50.eContents().get(0);
		private final RuleCall cEreignisseEreignisParserRuleCall_50_0_0 = (RuleCall)cEreignisseAssignment_50_0.eContents().get(0);
		private final Group cGroup_50_1 = (Group)cAlternatives_50.eContents().get(1);
		private final Keyword cKeineKeyword_50_1_0 = (Keyword)cGroup_50_1.eContents().get(0);
		private final Keyword cBekanntKeyword_50_1_1 = (Keyword)cGroup_50_1.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_51 = (Keyword)cGroup.eContents().get(51);
		private final Keyword cRightCurlyBracketKeyword_52 = (Keyword)cGroup.eContents().get(52);
		
		//Person:
		//	{Person}
		//	"Person" name=STRING "{"
		//	"Letzte" "Änderung:" letzteAenderung=DATUM "."
		//	"Vorname:" (vorname=STRING? | "unbekannt") "."
		//	"Mittelname:" (mittelname=STRING? | "unbekannt" | "-") "."
		//	"Nachname:" (nachname=STRING? | "unbekannt") "."
		//	"Geburtsname:" (geburtsname=STRING? | "unbekannt") "."
		//	"Rufname:" (rufname=STRING? | "unbekannt") "."
		//	"Geschlecht:" geschlecht=Geschlecht? "."
		//	"Geburtsdatum:" (geburtsDatum=DATUM? | "unbekannt") "."
		//	"Todesdatum:" (todesDatum=DATUM? | "unbekannt" | "lebend" | "vermisst") "."
		//	"Vater:" (vater=[Person|STRING]? | "unbekannt" | "unerfasst") "."
		//	"Mutter:" (mutter=[Person|STRING]? | "unbekannt" | "unerfasst") "."
		//	"Kinder:" (kinder=Kinder? | "keine") "."
		//	"Stiefkinder:" (stiefkinder=Kinder? | "keine") "."
		//	"Beziehungen:" "{" (beziehungen+=Beziehung+ | "keine") "}"
		//	"Ereignisse:" "{" (ereignisse+=Ereignis+ | "keine" "bekannt")
		//	"}"
		//	"}";
		@Override public ParserRule getRule() { return rule; }
		
		//{Person} "Person" name=STRING "{" "Letzte" "Änderung:" letzteAenderung=DATUM "." "Vorname:" (vorname=STRING? |
		//"unbekannt") "." "Mittelname:" (mittelname=STRING? | "unbekannt" | "-") "." "Nachname:" (nachname=STRING? |
		//"unbekannt") "." "Geburtsname:" (geburtsname=STRING? | "unbekannt") "." "Rufname:" (rufname=STRING? | "unbekannt") "."
		//"Geschlecht:" geschlecht=Geschlecht? "." "Geburtsdatum:" (geburtsDatum=DATUM? | "unbekannt") "." "Todesdatum:"
		//(todesDatum=DATUM? | "unbekannt" | "lebend" | "vermisst") "." "Vater:" (vater=[Person|STRING]? | "unbekannt" |
		//"unerfasst") "." "Mutter:" (mutter=[Person|STRING]? | "unbekannt" | "unerfasst") "." "Kinder:" (kinder=Kinder? |
		//"keine") "." "Stiefkinder:" (stiefkinder=Kinder? | "keine") "." "Beziehungen:" "{" (beziehungen+=Beziehung+ | "keine")
		//"}" "Ereignisse:" "{" (ereignisse+=Ereignis+ | "keine" "bekannt") "}" "}"
		public Group getGroup() { return cGroup; }
		
		//{Person}
		public Action getPersonAction_0() { return cPersonAction_0; }
		
		//"Person"
		public Keyword getPersonKeyword_1() { return cPersonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//"Letzte"
		public Keyword getLetzteKeyword_4() { return cLetzteKeyword_4; }
		
		//"Änderung:"
		public Keyword getÄnderungKeyword_5() { return cÄnderungKeyword_5; }
		
		//letzteAenderung=DATUM
		public Assignment getLetzteAenderungAssignment_6() { return cLetzteAenderungAssignment_6; }
		
		//DATUM
		public RuleCall getLetzteAenderungDATUMParserRuleCall_6_0() { return cLetzteAenderungDATUMParserRuleCall_6_0; }
		
		//"."
		public Keyword getFullStopKeyword_7() { return cFullStopKeyword_7; }
		
		//"Vorname:"
		public Keyword getVornameKeyword_8() { return cVornameKeyword_8; }
		
		//(vorname=STRING? | "unbekannt")
		public Alternatives getAlternatives_9() { return cAlternatives_9; }
		
		//vorname=STRING?
		public Assignment getVornameAssignment_9_0() { return cVornameAssignment_9_0; }
		
		//STRING
		public RuleCall getVornameSTRINGTerminalRuleCall_9_0_0() { return cVornameSTRINGTerminalRuleCall_9_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_9_1() { return cUnbekanntKeyword_9_1; }
		
		//"."
		public Keyword getFullStopKeyword_10() { return cFullStopKeyword_10; }
		
		//"Mittelname:"
		public Keyword getMittelnameKeyword_11() { return cMittelnameKeyword_11; }
		
		//(mittelname=STRING? | "unbekannt" | "-")
		public Alternatives getAlternatives_12() { return cAlternatives_12; }
		
		//mittelname=STRING?
		public Assignment getMittelnameAssignment_12_0() { return cMittelnameAssignment_12_0; }
		
		//STRING
		public RuleCall getMittelnameSTRINGTerminalRuleCall_12_0_0() { return cMittelnameSTRINGTerminalRuleCall_12_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_12_1() { return cUnbekanntKeyword_12_1; }
		
		//"-"
		public Keyword getHyphenMinusKeyword_12_2() { return cHyphenMinusKeyword_12_2; }
		
		//"."
		public Keyword getFullStopKeyword_13() { return cFullStopKeyword_13; }
		
		//"Nachname:"
		public Keyword getNachnameKeyword_14() { return cNachnameKeyword_14; }
		
		//(nachname=STRING? | "unbekannt")
		public Alternatives getAlternatives_15() { return cAlternatives_15; }
		
		//nachname=STRING?
		public Assignment getNachnameAssignment_15_0() { return cNachnameAssignment_15_0; }
		
		//STRING
		public RuleCall getNachnameSTRINGTerminalRuleCall_15_0_0() { return cNachnameSTRINGTerminalRuleCall_15_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_15_1() { return cUnbekanntKeyword_15_1; }
		
		//"."
		public Keyword getFullStopKeyword_16() { return cFullStopKeyword_16; }
		
		//"Geburtsname:"
		public Keyword getGeburtsnameKeyword_17() { return cGeburtsnameKeyword_17; }
		
		//(geburtsname=STRING? | "unbekannt")
		public Alternatives getAlternatives_18() { return cAlternatives_18; }
		
		//geburtsname=STRING?
		public Assignment getGeburtsnameAssignment_18_0() { return cGeburtsnameAssignment_18_0; }
		
		//STRING
		public RuleCall getGeburtsnameSTRINGTerminalRuleCall_18_0_0() { return cGeburtsnameSTRINGTerminalRuleCall_18_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_18_1() { return cUnbekanntKeyword_18_1; }
		
		//"."
		public Keyword getFullStopKeyword_19() { return cFullStopKeyword_19; }
		
		//"Rufname:"
		public Keyword getRufnameKeyword_20() { return cRufnameKeyword_20; }
		
		//(rufname=STRING? | "unbekannt")
		public Alternatives getAlternatives_21() { return cAlternatives_21; }
		
		//rufname=STRING?
		public Assignment getRufnameAssignment_21_0() { return cRufnameAssignment_21_0; }
		
		//STRING
		public RuleCall getRufnameSTRINGTerminalRuleCall_21_0_0() { return cRufnameSTRINGTerminalRuleCall_21_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_21_1() { return cUnbekanntKeyword_21_1; }
		
		//"."
		public Keyword getFullStopKeyword_22() { return cFullStopKeyword_22; }
		
		//"Geschlecht:"
		public Keyword getGeschlechtKeyword_23() { return cGeschlechtKeyword_23; }
		
		//geschlecht=Geschlecht?
		public Assignment getGeschlechtAssignment_24() { return cGeschlechtAssignment_24; }
		
		//Geschlecht
		public RuleCall getGeschlechtGeschlechtEnumRuleCall_24_0() { return cGeschlechtGeschlechtEnumRuleCall_24_0; }
		
		//"."
		public Keyword getFullStopKeyword_25() { return cFullStopKeyword_25; }
		
		//"Geburtsdatum:"
		public Keyword getGeburtsdatumKeyword_26() { return cGeburtsdatumKeyword_26; }
		
		//(geburtsDatum=DATUM? | "unbekannt")
		public Alternatives getAlternatives_27() { return cAlternatives_27; }
		
		//geburtsDatum=DATUM?
		public Assignment getGeburtsDatumAssignment_27_0() { return cGeburtsDatumAssignment_27_0; }
		
		//DATUM
		public RuleCall getGeburtsDatumDATUMParserRuleCall_27_0_0() { return cGeburtsDatumDATUMParserRuleCall_27_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_27_1() { return cUnbekanntKeyword_27_1; }
		
		//"."
		public Keyword getFullStopKeyword_28() { return cFullStopKeyword_28; }
		
		//"Todesdatum:"
		public Keyword getTodesdatumKeyword_29() { return cTodesdatumKeyword_29; }
		
		//(todesDatum=DATUM? | "unbekannt" | "lebend" | "vermisst")
		public Alternatives getAlternatives_30() { return cAlternatives_30; }
		
		//todesDatum=DATUM?
		public Assignment getTodesDatumAssignment_30_0() { return cTodesDatumAssignment_30_0; }
		
		//DATUM
		public RuleCall getTodesDatumDATUMParserRuleCall_30_0_0() { return cTodesDatumDATUMParserRuleCall_30_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_30_1() { return cUnbekanntKeyword_30_1; }
		
		//"lebend"
		public Keyword getLebendKeyword_30_2() { return cLebendKeyword_30_2; }
		
		//"vermisst"
		public Keyword getVermisstKeyword_30_3() { return cVermisstKeyword_30_3; }
		
		//"."
		public Keyword getFullStopKeyword_31() { return cFullStopKeyword_31; }
		
		//"Vater:"
		public Keyword getVaterKeyword_32() { return cVaterKeyword_32; }
		
		//(vater=[Person|STRING]? | "unbekannt" | "unerfasst")
		public Alternatives getAlternatives_33() { return cAlternatives_33; }
		
		//vater=[Person|STRING]?
		public Assignment getVaterAssignment_33_0() { return cVaterAssignment_33_0; }
		
		//[Person|STRING]
		public CrossReference getVaterPersonCrossReference_33_0_0() { return cVaterPersonCrossReference_33_0_0; }
		
		//STRING
		public RuleCall getVaterPersonSTRINGTerminalRuleCall_33_0_0_1() { return cVaterPersonSTRINGTerminalRuleCall_33_0_0_1; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_33_1() { return cUnbekanntKeyword_33_1; }
		
		//"unerfasst"
		public Keyword getUnerfasstKeyword_33_2() { return cUnerfasstKeyword_33_2; }
		
		//"."
		public Keyword getFullStopKeyword_34() { return cFullStopKeyword_34; }
		
		//"Mutter:"
		public Keyword getMutterKeyword_35() { return cMutterKeyword_35; }
		
		//(mutter=[Person|STRING]? | "unbekannt" | "unerfasst")
		public Alternatives getAlternatives_36() { return cAlternatives_36; }
		
		//mutter=[Person|STRING]?
		public Assignment getMutterAssignment_36_0() { return cMutterAssignment_36_0; }
		
		//[Person|STRING]
		public CrossReference getMutterPersonCrossReference_36_0_0() { return cMutterPersonCrossReference_36_0_0; }
		
		//STRING
		public RuleCall getMutterPersonSTRINGTerminalRuleCall_36_0_0_1() { return cMutterPersonSTRINGTerminalRuleCall_36_0_0_1; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_36_1() { return cUnbekanntKeyword_36_1; }
		
		//"unerfasst"
		public Keyword getUnerfasstKeyword_36_2() { return cUnerfasstKeyword_36_2; }
		
		//"."
		public Keyword getFullStopKeyword_37() { return cFullStopKeyword_37; }
		
		//"Kinder:"
		public Keyword getKinderKeyword_38() { return cKinderKeyword_38; }
		
		//(kinder=Kinder? | "keine")
		public Alternatives getAlternatives_39() { return cAlternatives_39; }
		
		//kinder=Kinder?
		public Assignment getKinderAssignment_39_0() { return cKinderAssignment_39_0; }
		
		//Kinder
		public RuleCall getKinderKinderParserRuleCall_39_0_0() { return cKinderKinderParserRuleCall_39_0_0; }
		
		//"keine"
		public Keyword getKeineKeyword_39_1() { return cKeineKeyword_39_1; }
		
		//"."
		public Keyword getFullStopKeyword_40() { return cFullStopKeyword_40; }
		
		//"Stiefkinder:"
		public Keyword getStiefkinderKeyword_41() { return cStiefkinderKeyword_41; }
		
		//(stiefkinder=Kinder? | "keine")
		public Alternatives getAlternatives_42() { return cAlternatives_42; }
		
		//stiefkinder=Kinder?
		public Assignment getStiefkinderAssignment_42_0() { return cStiefkinderAssignment_42_0; }
		
		//Kinder
		public RuleCall getStiefkinderKinderParserRuleCall_42_0_0() { return cStiefkinderKinderParserRuleCall_42_0_0; }
		
		//"keine"
		public Keyword getKeineKeyword_42_1() { return cKeineKeyword_42_1; }
		
		//"."
		public Keyword getFullStopKeyword_43() { return cFullStopKeyword_43; }
		
		//"Beziehungen:"
		public Keyword getBeziehungenKeyword_44() { return cBeziehungenKeyword_44; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_45() { return cLeftCurlyBracketKeyword_45; }
		
		//(beziehungen+=Beziehung+ | "keine")
		public Alternatives getAlternatives_46() { return cAlternatives_46; }
		
		//beziehungen+=Beziehung+
		public Assignment getBeziehungenAssignment_46_0() { return cBeziehungenAssignment_46_0; }
		
		//Beziehung
		public RuleCall getBeziehungenBeziehungParserRuleCall_46_0_0() { return cBeziehungenBeziehungParserRuleCall_46_0_0; }
		
		//"keine"
		public Keyword getKeineKeyword_46_1() { return cKeineKeyword_46_1; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_47() { return cRightCurlyBracketKeyword_47; }
		
		//"Ereignisse:"
		public Keyword getEreignisseKeyword_48() { return cEreignisseKeyword_48; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_49() { return cLeftCurlyBracketKeyword_49; }
		
		//(ereignisse+=Ereignis+ | "keine" "bekannt")
		public Alternatives getAlternatives_50() { return cAlternatives_50; }
		
		//ereignisse+=Ereignis+
		public Assignment getEreignisseAssignment_50_0() { return cEreignisseAssignment_50_0; }
		
		//Ereignis
		public RuleCall getEreignisseEreignisParserRuleCall_50_0_0() { return cEreignisseEreignisParserRuleCall_50_0_0; }
		
		//"keine" "bekannt"
		public Group getGroup_50_1() { return cGroup_50_1; }
		
		//"keine"
		public Keyword getKeineKeyword_50_1_0() { return cKeineKeyword_50_1_0; }
		
		//"bekannt"
		public Keyword getBekanntKeyword_50_1_1() { return cBekanntKeyword_50_1_1; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_51() { return cRightCurlyBracketKeyword_51; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_52() { return cRightCurlyBracketKeyword_52; }
	}
	public class EreignisElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Ereignis");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSchulausbildungParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTaetigkeitParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Ereignis:
		//	Schulausbildung | Taetigkeit // | Lehre | Armeedienst | Unfall | Krankheit | NeueAdresse
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Schulausbildung | Taetigkeit
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Schulausbildung
		public RuleCall getSchulausbildungParserRuleCall_0() { return cSchulausbildungParserRuleCall_0; }
		
		//Taetigkeit
		public RuleCall getTaetigkeitParserRuleCall_1() { return cTaetigkeitParserRuleCall_1; }
	}
	public class SchulausbildungElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Schulausbildung");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSchulausbildungAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSchulausbildungKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cVonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cVonAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cVonDATUMParserRuleCall_3_0_0 = (RuleCall)cVonAssignment_3_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		private final Keyword cBisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Assignment cBisAssignment_5_0 = (Assignment)cAlternatives_5.eContents().get(0);
		private final RuleCall cBisDATUMParserRuleCall_5_0_0 = (RuleCall)cBisAssignment_5_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final Keyword cAbschlussKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Alternatives cAlternatives_7 = (Alternatives)cGroup.eContents().get(7);
		private final Assignment cAbschlussAssignment_7_0 = (Assignment)cAlternatives_7.eContents().get(0);
		private final RuleCall cAbschlussSTRINGTerminalRuleCall_7_0_0 = (RuleCall)cAbschlussAssignment_7_0.eContents().get(0);
		private final Keyword cOhneKeyword_7_1 = (Keyword)cAlternatives_7.eContents().get(1);
		private final Keyword cAbgebrochenKeyword_7_2 = (Keyword)cAlternatives_7.eContents().get(2);
		private final Keyword cFullStopKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Schulausbildung:
		//	{Schulausbildung}
		//	"Schulausbildung:" "von" (von=DATUM? | "unbekannt") "bis" (bis=DATUM? | "unbekannt")
		//	"Abschluss:" (abschluss=STRING? | "ohne" | "abgebrochen")
		//	".";
		@Override public ParserRule getRule() { return rule; }
		
		//{Schulausbildung} "Schulausbildung:" "von" (von=DATUM? | "unbekannt") "bis" (bis=DATUM? | "unbekannt") "Abschluss:"
		//(abschluss=STRING? | "ohne" | "abgebrochen") "."
		public Group getGroup() { return cGroup; }
		
		//{Schulausbildung}
		public Action getSchulausbildungAction_0() { return cSchulausbildungAction_0; }
		
		//"Schulausbildung:"
		public Keyword getSchulausbildungKeyword_1() { return cSchulausbildungKeyword_1; }
		
		//"von"
		public Keyword getVonKeyword_2() { return cVonKeyword_2; }
		
		//(von=DATUM? | "unbekannt")
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//von=DATUM?
		public Assignment getVonAssignment_3_0() { return cVonAssignment_3_0; }
		
		//DATUM
		public RuleCall getVonDATUMParserRuleCall_3_0_0() { return cVonDATUMParserRuleCall_3_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_3_1() { return cUnbekanntKeyword_3_1; }
		
		//"bis"
		public Keyword getBisKeyword_4() { return cBisKeyword_4; }
		
		//(bis=DATUM? | "unbekannt")
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//bis=DATUM?
		public Assignment getBisAssignment_5_0() { return cBisAssignment_5_0; }
		
		//DATUM
		public RuleCall getBisDATUMParserRuleCall_5_0_0() { return cBisDATUMParserRuleCall_5_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_5_1() { return cUnbekanntKeyword_5_1; }
		
		//"Abschluss:"
		public Keyword getAbschlussKeyword_6() { return cAbschlussKeyword_6; }
		
		//(abschluss=STRING? | "ohne" | "abgebrochen")
		public Alternatives getAlternatives_7() { return cAlternatives_7; }
		
		//abschluss=STRING?
		public Assignment getAbschlussAssignment_7_0() { return cAbschlussAssignment_7_0; }
		
		//STRING
		public RuleCall getAbschlussSTRINGTerminalRuleCall_7_0_0() { return cAbschlussSTRINGTerminalRuleCall_7_0_0; }
		
		//"ohne"
		public Keyword getOhneKeyword_7_1() { return cOhneKeyword_7_1; }
		
		//"abgebrochen"
		public Keyword getAbgebrochenKeyword_7_2() { return cAbgebrochenKeyword_7_2; }
		
		//"."
		public Keyword getFullStopKeyword_8() { return cFullStopKeyword_8; }
	}
	public class TaetigkeitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Taetigkeit");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTaetigkeitAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTätigkeitKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAlsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cBerufAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cBerufSTRINGTerminalRuleCall_3_0_0 = (RuleCall)cBerufAssignment_3_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		private final Keyword cBeiKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Assignment cArbeitgeberAssignment_5_0 = (Assignment)cAlternatives_5.eContents().get(0);
		private final RuleCall cArbeitgeberSTRINGTerminalRuleCall_5_0_0 = (RuleCall)cArbeitgeberAssignment_5_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final Keyword cInKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Alternatives cAlternatives_7 = (Alternatives)cGroup.eContents().get(7);
		private final Assignment cOrtAssignment_7_0 = (Assignment)cAlternatives_7.eContents().get(0);
		private final RuleCall cOrtSTRINGTerminalRuleCall_7_0_0 = (RuleCall)cOrtAssignment_7_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_7_1 = (Keyword)cAlternatives_7.eContents().get(1);
		private final Keyword cVonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Alternatives cAlternatives_9 = (Alternatives)cGroup.eContents().get(9);
		private final Assignment cVonAssignment_9_0 = (Assignment)cAlternatives_9.eContents().get(0);
		private final RuleCall cVonDATUMParserRuleCall_9_0_0 = (RuleCall)cVonAssignment_9_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_9_1 = (Keyword)cAlternatives_9.eContents().get(1);
		private final Keyword cBisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Alternatives cAlternatives_11 = (Alternatives)cGroup.eContents().get(11);
		private final Assignment cBisAssignment_11_0 = (Assignment)cAlternatives_11.eContents().get(0);
		private final RuleCall cBisDATUMParserRuleCall_11_0_0 = (RuleCall)cBisAssignment_11_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_11_1 = (Keyword)cAlternatives_11.eContents().get(1);
		private final Keyword cFullStopKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Taetigkeit:
		//	{Taetigkeit}
		//	"Tätigkeit:" "als" (beruf=STRING? | "unbekannt")
		//	"bei" (arbeitgeber=STRING? | "unbekannt")
		//	"in" (ort=STRING? | "unbekannt")
		//	"von" (von=DATUM? | "unbekannt") "bis" (bis=DATUM? | "unbekannt") ".";
		@Override public ParserRule getRule() { return rule; }
		
		//{Taetigkeit} "Tätigkeit:" "als" (beruf=STRING? | "unbekannt") "bei" (arbeitgeber=STRING? | "unbekannt") "in"
		//(ort=STRING? | "unbekannt") "von" (von=DATUM? | "unbekannt") "bis" (bis=DATUM? | "unbekannt") "."
		public Group getGroup() { return cGroup; }
		
		//{Taetigkeit}
		public Action getTaetigkeitAction_0() { return cTaetigkeitAction_0; }
		
		//"Tätigkeit:"
		public Keyword getTätigkeitKeyword_1() { return cTätigkeitKeyword_1; }
		
		//"als"
		public Keyword getAlsKeyword_2() { return cAlsKeyword_2; }
		
		//(beruf=STRING? | "unbekannt")
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//beruf=STRING?
		public Assignment getBerufAssignment_3_0() { return cBerufAssignment_3_0; }
		
		//STRING
		public RuleCall getBerufSTRINGTerminalRuleCall_3_0_0() { return cBerufSTRINGTerminalRuleCall_3_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_3_1() { return cUnbekanntKeyword_3_1; }
		
		//"bei"
		public Keyword getBeiKeyword_4() { return cBeiKeyword_4; }
		
		//(arbeitgeber=STRING? | "unbekannt")
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//arbeitgeber=STRING?
		public Assignment getArbeitgeberAssignment_5_0() { return cArbeitgeberAssignment_5_0; }
		
		//STRING
		public RuleCall getArbeitgeberSTRINGTerminalRuleCall_5_0_0() { return cArbeitgeberSTRINGTerminalRuleCall_5_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_5_1() { return cUnbekanntKeyword_5_1; }
		
		//"in"
		public Keyword getInKeyword_6() { return cInKeyword_6; }
		
		//(ort=STRING? | "unbekannt")
		public Alternatives getAlternatives_7() { return cAlternatives_7; }
		
		//ort=STRING?
		public Assignment getOrtAssignment_7_0() { return cOrtAssignment_7_0; }
		
		//STRING
		public RuleCall getOrtSTRINGTerminalRuleCall_7_0_0() { return cOrtSTRINGTerminalRuleCall_7_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_7_1() { return cUnbekanntKeyword_7_1; }
		
		//"von"
		public Keyword getVonKeyword_8() { return cVonKeyword_8; }
		
		//(von=DATUM? | "unbekannt")
		public Alternatives getAlternatives_9() { return cAlternatives_9; }
		
		//von=DATUM?
		public Assignment getVonAssignment_9_0() { return cVonAssignment_9_0; }
		
		//DATUM
		public RuleCall getVonDATUMParserRuleCall_9_0_0() { return cVonDATUMParserRuleCall_9_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_9_1() { return cUnbekanntKeyword_9_1; }
		
		//"bis"
		public Keyword getBisKeyword_10() { return cBisKeyword_10; }
		
		//(bis=DATUM? | "unbekannt")
		public Alternatives getAlternatives_11() { return cAlternatives_11; }
		
		//bis=DATUM?
		public Assignment getBisAssignment_11_0() { return cBisAssignment_11_0; }
		
		//DATUM
		public RuleCall getBisDATUMParserRuleCall_11_0_0() { return cBisDATUMParserRuleCall_11_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_11_1() { return cUnbekanntKeyword_11_1; }
		
		//"."
		public Keyword getFullStopKeyword_12() { return cFullStopKeyword_12; }
	}
	public class KinderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Kinder");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cKinderAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cKindAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final CrossReference cKindPersonCrossReference_1_0_0 = (CrossReference)cKindAssignment_1_0.eContents().get(0);
		private final RuleCall cKindPersonSTRINGTerminalRuleCall_1_0_0_1 = (RuleCall)cKindPersonCrossReference_1_0_0.eContents().get(1);
		private final Keyword cUnbekanntKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Keyword cUnerfasstKeyword_1_2 = (Keyword)cAlternatives_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cNextAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNextKinderParserRuleCall_2_1_0 = (RuleCall)cNextAssignment_2_1.eContents().get(0);
		
		//Kinder:
		//	{Kinder} (kind=[Person|STRING] | "unbekannt" | "unerfasst") ("," next=Kinder)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Kinder} (kind=[Person|STRING] | "unbekannt" | "unerfasst") ("," next=Kinder)?
		public Group getGroup() { return cGroup; }
		
		//{Kinder}
		public Action getKinderAction_0() { return cKinderAction_0; }
		
		//(kind=[Person|STRING] | "unbekannt" | "unerfasst")
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//kind=[Person|STRING]
		public Assignment getKindAssignment_1_0() { return cKindAssignment_1_0; }
		
		//[Person|STRING]
		public CrossReference getKindPersonCrossReference_1_0_0() { return cKindPersonCrossReference_1_0_0; }
		
		//STRING
		public RuleCall getKindPersonSTRINGTerminalRuleCall_1_0_0_1() { return cKindPersonSTRINGTerminalRuleCall_1_0_0_1; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_1_1() { return cUnbekanntKeyword_1_1; }
		
		//"unerfasst"
		public Keyword getUnerfasstKeyword_1_2() { return cUnerfasstKeyword_1_2; }
		
		//("," next=Kinder)?
		public Group getGroup_2() { return cGroup_2; }
		
		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//next=Kinder
		public Assignment getNextAssignment_2_1() { return cNextAssignment_2_1; }
		
		//Kinder
		public RuleCall getNextKinderParserRuleCall_2_1_0() { return cNextKinderParserRuleCall_2_1_0; }
	}
	public class BeziehungElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Beziehung");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBeziehungAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBeziehungKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMitKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cBeziehungAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final CrossReference cBeziehungPersonCrossReference_3_0_0 = (CrossReference)cBeziehungAssignment_3_0.eContents().get(0);
		private final RuleCall cBeziehungPersonSTRINGTerminalRuleCall_3_0_0_1 = (RuleCall)cBeziehungPersonCrossReference_3_0_0.eContents().get(1);
		private final Keyword cUnbekanntKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		private final Keyword cUnerfasstKeyword_3_2 = (Keyword)cAlternatives_3.eContents().get(2);
		private final Keyword cFullStopKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cVonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final Assignment cVonDatumAssignment_6_0 = (Assignment)cAlternatives_6.eContents().get(0);
		private final RuleCall cVonDatumDATUMParserRuleCall_6_0_0 = (RuleCall)cVonDatumAssignment_6_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_6_1 = (Keyword)cAlternatives_6.eContents().get(1);
		private final Keyword cBisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Alternatives cAlternatives_8 = (Alternatives)cGroup.eContents().get(8);
		private final Assignment cBisDatumAssignment_8_0 = (Assignment)cAlternatives_8.eContents().get(0);
		private final RuleCall cBisDatumDATUMParserRuleCall_8_0_0 = (RuleCall)cBisDatumAssignment_8_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_8_1 = (Keyword)cAlternatives_8.eContents().get(1);
		private final Keyword cAndauerndKeyword_8_2 = (Keyword)cAlternatives_8.eContents().get(2);
		private final Keyword cFullStopKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cHochzeitKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Alternatives cAlternatives_11 = (Alternatives)cGroup.eContents().get(11);
		private final Assignment cHochzeitstagAssignment_11_0 = (Assignment)cAlternatives_11.eContents().get(0);
		private final RuleCall cHochzeitstagDATUMParserRuleCall_11_0_0 = (RuleCall)cHochzeitstagAssignment_11_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_11_1 = (Keyword)cAlternatives_11.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_11_2 = (Keyword)cAlternatives_11.eContents().get(2);
		private final Keyword cFullStopKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cScheidungKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Alternatives cAlternatives_14 = (Alternatives)cGroup.eContents().get(14);
		private final Assignment cScheidungstagAssignment_14_0 = (Assignment)cAlternatives_14.eContents().get(0);
		private final RuleCall cScheidungstagDATUMParserRuleCall_14_0_0 = (RuleCall)cScheidungstagAssignment_14_0.eContents().get(0);
		private final Keyword cUnbekanntKeyword_14_1 = (Keyword)cAlternatives_14.eContents().get(1);
		private final Keyword cUnabsehbarKeyword_14_2 = (Keyword)cAlternatives_14.eContents().get(2);
		private final Keyword cDemnächstKeyword_14_3 = (Keyword)cAlternatives_14.eContents().get(3);
		private final Keyword cHyphenMinusKeyword_14_4 = (Keyword)cAlternatives_14.eContents().get(4);
		private final Keyword cFullStopKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Beziehung:
		//	{Beziehung}
		//	"Beziehung:" "mit" (beziehung=[Person|STRING] | "unbekannt" | "unerfasst") "."
		//	"von:" (vonDatum=DATUM? | "unbekannt") "bis:" (bisDatum=DATUM? | "unbekannt" | "andauernd") "."
		//	"Hochzeit:" (hochzeitstag=DATUM? | "unbekannt" | "-") "."
		//	"Scheidung:" (scheidungstag=DATUM? | "unbekannt" | "unabsehbar" | "demnächst" | "-") ".";
		@Override public ParserRule getRule() { return rule; }
		
		//{Beziehung} "Beziehung:" "mit" (beziehung=[Person|STRING] | "unbekannt" | "unerfasst") "." "von:" (vonDatum=DATUM? |
		//"unbekannt") "bis:" (bisDatum=DATUM? | "unbekannt" | "andauernd") "." "Hochzeit:" (hochzeitstag=DATUM? | "unbekannt" |
		//"-") "." "Scheidung:" (scheidungstag=DATUM? | "unbekannt" | "unabsehbar" | "demnächst" | "-") "."
		public Group getGroup() { return cGroup; }
		
		//{Beziehung}
		public Action getBeziehungAction_0() { return cBeziehungAction_0; }
		
		//"Beziehung:"
		public Keyword getBeziehungKeyword_1() { return cBeziehungKeyword_1; }
		
		//"mit"
		public Keyword getMitKeyword_2() { return cMitKeyword_2; }
		
		//(beziehung=[Person|STRING] | "unbekannt" | "unerfasst")
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//beziehung=[Person|STRING]
		public Assignment getBeziehungAssignment_3_0() { return cBeziehungAssignment_3_0; }
		
		//[Person|STRING]
		public CrossReference getBeziehungPersonCrossReference_3_0_0() { return cBeziehungPersonCrossReference_3_0_0; }
		
		//STRING
		public RuleCall getBeziehungPersonSTRINGTerminalRuleCall_3_0_0_1() { return cBeziehungPersonSTRINGTerminalRuleCall_3_0_0_1; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_3_1() { return cUnbekanntKeyword_3_1; }
		
		//"unerfasst"
		public Keyword getUnerfasstKeyword_3_2() { return cUnerfasstKeyword_3_2; }
		
		//"."
		public Keyword getFullStopKeyword_4() { return cFullStopKeyword_4; }
		
		//"von:"
		public Keyword getVonKeyword_5() { return cVonKeyword_5; }
		
		//(vonDatum=DATUM? | "unbekannt")
		public Alternatives getAlternatives_6() { return cAlternatives_6; }
		
		//vonDatum=DATUM?
		public Assignment getVonDatumAssignment_6_0() { return cVonDatumAssignment_6_0; }
		
		//DATUM
		public RuleCall getVonDatumDATUMParserRuleCall_6_0_0() { return cVonDatumDATUMParserRuleCall_6_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_6_1() { return cUnbekanntKeyword_6_1; }
		
		//"bis:"
		public Keyword getBisKeyword_7() { return cBisKeyword_7; }
		
		//(bisDatum=DATUM? | "unbekannt" | "andauernd")
		public Alternatives getAlternatives_8() { return cAlternatives_8; }
		
		//bisDatum=DATUM?
		public Assignment getBisDatumAssignment_8_0() { return cBisDatumAssignment_8_0; }
		
		//DATUM
		public RuleCall getBisDatumDATUMParserRuleCall_8_0_0() { return cBisDatumDATUMParserRuleCall_8_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_8_1() { return cUnbekanntKeyword_8_1; }
		
		//"andauernd"
		public Keyword getAndauerndKeyword_8_2() { return cAndauerndKeyword_8_2; }
		
		//"."
		public Keyword getFullStopKeyword_9() { return cFullStopKeyword_9; }
		
		//"Hochzeit:"
		public Keyword getHochzeitKeyword_10() { return cHochzeitKeyword_10; }
		
		//(hochzeitstag=DATUM? | "unbekannt" | "-")
		public Alternatives getAlternatives_11() { return cAlternatives_11; }
		
		//hochzeitstag=DATUM?
		public Assignment getHochzeitstagAssignment_11_0() { return cHochzeitstagAssignment_11_0; }
		
		//DATUM
		public RuleCall getHochzeitstagDATUMParserRuleCall_11_0_0() { return cHochzeitstagDATUMParserRuleCall_11_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_11_1() { return cUnbekanntKeyword_11_1; }
		
		//"-"
		public Keyword getHyphenMinusKeyword_11_2() { return cHyphenMinusKeyword_11_2; }
		
		//"."
		public Keyword getFullStopKeyword_12() { return cFullStopKeyword_12; }
		
		//"Scheidung:"
		public Keyword getScheidungKeyword_13() { return cScheidungKeyword_13; }
		
		//(scheidungstag=DATUM? | "unbekannt" | "unabsehbar" | "demnächst" | "-")
		public Alternatives getAlternatives_14() { return cAlternatives_14; }
		
		//scheidungstag=DATUM?
		public Assignment getScheidungstagAssignment_14_0() { return cScheidungstagAssignment_14_0; }
		
		//DATUM
		public RuleCall getScheidungstagDATUMParserRuleCall_14_0_0() { return cScheidungstagDATUMParserRuleCall_14_0_0; }
		
		//"unbekannt"
		public Keyword getUnbekanntKeyword_14_1() { return cUnbekanntKeyword_14_1; }
		
		//"unabsehbar"
		public Keyword getUnabsehbarKeyword_14_2() { return cUnabsehbarKeyword_14_2; }
		
		//"demnächst"
		public Keyword getDemnächstKeyword_14_3() { return cDemnächstKeyword_14_3; }
		
		//"-"
		public Keyword getHyphenMinusKeyword_14_4() { return cHyphenMinusKeyword_14_4; }
		
		//"."
		public Keyword getFullStopKeyword_15() { return cFullStopKeyword_15; }
	}
	public class FamilienbuchElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Familienbuch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFamilienbuchKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFamilieKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFamilieAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFamilieSTRINGTerminalRuleCall_4_0 = (RuleCall)cFamilieAssignment_4.eContents().get(0);
		private final Keyword cFullStopKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cPersonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPersonAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cPersonPersonCrossReference_7_0 = (CrossReference)cPersonAssignment_7.eContents().get(0);
		private final RuleCall cPersonPersonSTRINGTerminalRuleCall_7_0_1 = (RuleCall)cPersonPersonCrossReference_7_0.eContents().get(1);
		private final Keyword cFullStopKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cVersionKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cVersionAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cVersionVERSIONParserRuleCall_10_0 = (RuleCall)cVersionAssignment_10.eContents().get(0);
		private final Keyword cFullStopKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cTitelKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cTitelAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cTitelSTRINGTerminalRuleCall_13_0 = (RuleCall)cTitelAssignment_13.eContents().get(0);
		private final Keyword cFullStopKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cVorwortKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cLeftCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cVorwortAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cVorwortSTRINGTerminalRuleCall_17_0 = (RuleCall)cVorwortAssignment_17.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cAutorKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cLeftCurlyBracketKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cAutorAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cAutorAutorParserRuleCall_21_0 = (RuleCall)cAutorAssignment_21.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Keyword cFamilienKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Keyword cLeftCurlyBracketKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Assignment cFamilienAssignment_25 = (Assignment)cGroup.eContents().get(25);
		private final RuleCall cFamilienFamilienImportParserRuleCall_25_0 = (RuleCall)cFamilienAssignment_25.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_26 = (Keyword)cGroup.eContents().get(26);
		
		//Familienbuch:
		//	"Familienbuch" name=ID ";"
		//	"Familie:" familie=STRING "."
		//	"Person:" person=[Person|STRING] "."
		//	"Version:" version=VERSION "."
		//	"Titel:" titel=STRING "."
		//	"Vorwort:" "{" vorwort=STRING "}"
		//	"Autor:" "{" autor=Autor "}"
		//	"Familien:" "{"
		//	familien+=FamilienImport+
		//	"}";
		@Override public ParserRule getRule() { return rule; }
		
		//"Familienbuch" name=ID ";" "Familie:" familie=STRING "." "Person:" person=[Person|STRING] "." "Version:" version=VERSION
		//"." "Titel:" titel=STRING "." "Vorwort:" "{" vorwort=STRING "}" "Autor:" "{" autor=Autor "}" "Familien:" "{"
		//familien+=FamilienImport+ "}"
		public Group getGroup() { return cGroup; }
		
		//"Familienbuch"
		public Keyword getFamilienbuchKeyword_0() { return cFamilienbuchKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//";"
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
		
		//"Familie:"
		public Keyword getFamilieKeyword_3() { return cFamilieKeyword_3; }
		
		//familie=STRING
		public Assignment getFamilieAssignment_4() { return cFamilieAssignment_4; }
		
		//STRING
		public RuleCall getFamilieSTRINGTerminalRuleCall_4_0() { return cFamilieSTRINGTerminalRuleCall_4_0; }
		
		//"."
		public Keyword getFullStopKeyword_5() { return cFullStopKeyword_5; }
		
		//"Person:"
		public Keyword getPersonKeyword_6() { return cPersonKeyword_6; }
		
		//person=[Person|STRING]
		public Assignment getPersonAssignment_7() { return cPersonAssignment_7; }
		
		//[Person|STRING]
		public CrossReference getPersonPersonCrossReference_7_0() { return cPersonPersonCrossReference_7_0; }
		
		//STRING
		public RuleCall getPersonPersonSTRINGTerminalRuleCall_7_0_1() { return cPersonPersonSTRINGTerminalRuleCall_7_0_1; }
		
		//"."
		public Keyword getFullStopKeyword_8() { return cFullStopKeyword_8; }
		
		//"Version:"
		public Keyword getVersionKeyword_9() { return cVersionKeyword_9; }
		
		//version=VERSION
		public Assignment getVersionAssignment_10() { return cVersionAssignment_10; }
		
		//VERSION
		public RuleCall getVersionVERSIONParserRuleCall_10_0() { return cVersionVERSIONParserRuleCall_10_0; }
		
		//"."
		public Keyword getFullStopKeyword_11() { return cFullStopKeyword_11; }
		
		//"Titel:"
		public Keyword getTitelKeyword_12() { return cTitelKeyword_12; }
		
		//titel=STRING
		public Assignment getTitelAssignment_13() { return cTitelAssignment_13; }
		
		//STRING
		public RuleCall getTitelSTRINGTerminalRuleCall_13_0() { return cTitelSTRINGTerminalRuleCall_13_0; }
		
		//"."
		public Keyword getFullStopKeyword_14() { return cFullStopKeyword_14; }
		
		//"Vorwort:"
		public Keyword getVorwortKeyword_15() { return cVorwortKeyword_15; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_16() { return cLeftCurlyBracketKeyword_16; }
		
		//vorwort=STRING
		public Assignment getVorwortAssignment_17() { return cVorwortAssignment_17; }
		
		//STRING
		public RuleCall getVorwortSTRINGTerminalRuleCall_17_0() { return cVorwortSTRINGTerminalRuleCall_17_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
		
		//"Autor:"
		public Keyword getAutorKeyword_19() { return cAutorKeyword_19; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_20() { return cLeftCurlyBracketKeyword_20; }
		
		//autor=Autor
		public Assignment getAutorAssignment_21() { return cAutorAssignment_21; }
		
		//Autor
		public RuleCall getAutorAutorParserRuleCall_21_0() { return cAutorAutorParserRuleCall_21_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_22() { return cRightCurlyBracketKeyword_22; }
		
		//"Familien:"
		public Keyword getFamilienKeyword_23() { return cFamilienKeyword_23; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_24() { return cLeftCurlyBracketKeyword_24; }
		
		//familien+=FamilienImport+
		public Assignment getFamilienAssignment_25() { return cFamilienAssignment_25; }
		
		//FamilienImport
		public RuleCall getFamilienFamilienImportParserRuleCall_25_0() { return cFamilienFamilienImportParserRuleCall_25_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_26() { return cRightCurlyBracketKeyword_26; }
	}
	public class FamilienImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.FamilienImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFamilieKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFamilieAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cFamilieFamilieCrossReference_2_0 = (CrossReference)cFamilieAssignment_2.eContents().get(0);
		private final RuleCall cFamilieFamilieIDTerminalRuleCall_2_0_1 = (RuleCall)cFamilieFamilieCrossReference_2_0.eContents().get(1);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//FamilienImport:
		//	"import" "familie" familie=[Familie] '.';
		@Override public ParserRule getRule() { return rule; }
		
		//"import" "familie" familie=[Familie] '.'
		public Group getGroup() { return cGroup; }
		
		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//"familie"
		public Keyword getFamilieKeyword_1() { return cFamilieKeyword_1; }
		
		//familie=[Familie]
		public Assignment getFamilieAssignment_2() { return cFamilieAssignment_2; }
		
		//[Familie]
		public CrossReference getFamilieFamilieCrossReference_2_0() { return cFamilieFamilieCrossReference_2_0; }
		
		//ID
		public RuleCall getFamilieFamilieIDTerminalRuleCall_2_0_1() { return cFamilieFamilieIDTerminalRuleCall_2_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
	}
	public class AutorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Autor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVornameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVornameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVornameSTRINGTerminalRuleCall_1_0 = (RuleCall)cVornameAssignment_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNachnameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNachnameSTRINGTerminalRuleCall_4_0 = (RuleCall)cNachnameAssignment_4.eContents().get(0);
		private final Keyword cFullStopKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cOrganisationKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cOrganisationsNameAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cOrganisationsNameSTRINGTerminalRuleCall_7_0 = (RuleCall)cOrganisationsNameAssignment_7.eContents().get(0);
		private final Keyword cFullStopKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Autor:
		//	"Vorname:" vorname=STRING "."
		//	"Name:" nachname=STRING "."
		//	"Organisation" organisationsName=STRING? ".";
		@Override public ParserRule getRule() { return rule; }
		
		//"Vorname:" vorname=STRING "." "Name:" nachname=STRING "." "Organisation" organisationsName=STRING? "."
		public Group getGroup() { return cGroup; }
		
		//"Vorname:"
		public Keyword getVornameKeyword_0() { return cVornameKeyword_0; }
		
		//vorname=STRING
		public Assignment getVornameAssignment_1() { return cVornameAssignment_1; }
		
		//STRING
		public RuleCall getVornameSTRINGTerminalRuleCall_1_0() { return cVornameSTRINGTerminalRuleCall_1_0; }
		
		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//"Name:"
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//nachname=STRING
		public Assignment getNachnameAssignment_4() { return cNachnameAssignment_4; }
		
		//STRING
		public RuleCall getNachnameSTRINGTerminalRuleCall_4_0() { return cNachnameSTRINGTerminalRuleCall_4_0; }
		
		//"."
		public Keyword getFullStopKeyword_5() { return cFullStopKeyword_5; }
		
		//"Organisation"
		public Keyword getOrganisationKeyword_6() { return cOrganisationKeyword_6; }
		
		//organisationsName=STRING?
		public Assignment getOrganisationsNameAssignment_7() { return cOrganisationsNameAssignment_7; }
		
		//STRING
		public RuleCall getOrganisationsNameSTRINGTerminalRuleCall_7_0() { return cOrganisationsNameSTRINGTerminalRuleCall_7_0; }
		
		//"."
		public Keyword getFullStopKeyword_8() { return cFullStopKeyword_8; }
	}
	public class VERSIONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.VERSION");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//VERSION:
		//	INT "." INT "." INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT "." INT "." INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
		
		//"."
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4() { return cINTTerminalRuleCall_4; }
	}
	public class DATUMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.DATUM");
		private final RuleCall cDATETerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//DATUM:
		//	DATE;
		@Override public ParserRule getRule() { return rule; }
		
		//DATE
		public RuleCall getDATETerminalRuleCall() { return cDATETerminalRuleCall; }
	}
	
	public class GeschlechtElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.Geschlecht");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUnbekanntEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUnbekanntUnbekanntKeyword_0_0 = (Keyword)cUnbekanntEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMaennlichEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMaennlichMännlichKeyword_1_0 = (Keyword)cMaennlichEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cWeiblichEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cWeiblichWeiblichKeyword_2_0 = (Keyword)cWeiblichEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Geschlecht:
		//	unbekannt | maennlich='männlich'
		//	| weiblich;
		public EnumRule getRule() { return rule; }
		
		//unbekannt | maennlich='männlich' | weiblich
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//unbekannt
		public EnumLiteralDeclaration getUnbekanntEnumLiteralDeclaration_0() { return cUnbekanntEnumLiteralDeclaration_0; }
		
		//'unbekannt'
		public Keyword getUnbekanntUnbekanntKeyword_0_0() { return cUnbekanntUnbekanntKeyword_0_0; }
		
		//maennlich='männlich'
		public EnumLiteralDeclaration getMaennlichEnumLiteralDeclaration_1() { return cMaennlichEnumLiteralDeclaration_1; }
		
		//'männlich'
		public Keyword getMaennlichMännlichKeyword_1_0() { return cMaennlichMännlichKeyword_1_0; }
		
		//weiblich
		public EnumLiteralDeclaration getWeiblichEnumLiteralDeclaration_2() { return cWeiblichEnumLiteralDeclaration_2; }
		
		//'weiblich'
		public Keyword getWeiblichWeiblichKeyword_2_0() { return cWeiblichWeiblichKeyword_2_0; }
	}
	
	private final ModelElements pModel;
	private final DateiartElements pDateiart;
	private final FamilieElements pFamilie;
	private final PersonElements pPerson;
	private final EreignisElements pEreignis;
	private final SchulausbildungElements pSchulausbildung;
	private final TaetigkeitElements pTaetigkeit;
	private final KinderElements pKinder;
	private final BeziehungElements pBeziehung;
	private final FamilienbuchElements pFamilienbuch;
	private final FamilienImportElements pFamilienImport;
	private final AutorElements pAutor;
	private final GeschlechtElements eGeschlecht;
	private final VERSIONElements pVERSION;
	private final DATUMElements pDATUM;
	private final TerminalRule tDATE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AhnenGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pDateiart = new DateiartElements();
		this.pFamilie = new FamilieElements();
		this.pPerson = new PersonElements();
		this.pEreignis = new EreignisElements();
		this.pSchulausbildung = new SchulausbildungElements();
		this.pTaetigkeit = new TaetigkeitElements();
		this.pKinder = new KinderElements();
		this.pBeziehung = new BeziehungElements();
		this.pFamilienbuch = new FamilienbuchElements();
		this.pFamilienImport = new FamilienImportElements();
		this.pAutor = new AutorElements();
		this.eGeschlecht = new GeschlechtElements();
		this.pVERSION = new VERSIONElements();
		this.pDATUM = new DATUMElements();
		this.tDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "com.github.funthomas424242.dsl.Ahnen.DATE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.github.funthomas424242.dsl.Ahnen".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	datei=Dateiart;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Dateiart:
	//	buch=Familienbuch | familie=Familie;
	public DateiartElements getDateiartAccess() {
		return pDateiart;
	}
	
	public ParserRule getDateiartRule() {
		return getDateiartAccess().getRule();
	}
	
	//Familie:
	//	{Familie}
	//	"Familie" name=ID ";"
	//	personen+=Person+;
	public FamilieElements getFamilieAccess() {
		return pFamilie;
	}
	
	public ParserRule getFamilieRule() {
		return getFamilieAccess().getRule();
	}
	
	//Person:
	//	{Person}
	//	"Person" name=STRING "{"
	//	"Letzte" "Änderung:" letzteAenderung=DATUM "."
	//	"Vorname:" (vorname=STRING? | "unbekannt") "."
	//	"Mittelname:" (mittelname=STRING? | "unbekannt" | "-") "."
	//	"Nachname:" (nachname=STRING? | "unbekannt") "."
	//	"Geburtsname:" (geburtsname=STRING? | "unbekannt") "."
	//	"Rufname:" (rufname=STRING? | "unbekannt") "."
	//	"Geschlecht:" geschlecht=Geschlecht? "."
	//	"Geburtsdatum:" (geburtsDatum=DATUM? | "unbekannt") "."
	//	"Todesdatum:" (todesDatum=DATUM? | "unbekannt" | "lebend" | "vermisst") "."
	//	"Vater:" (vater=[Person|STRING]? | "unbekannt" | "unerfasst") "."
	//	"Mutter:" (mutter=[Person|STRING]? | "unbekannt" | "unerfasst") "."
	//	"Kinder:" (kinder=Kinder? | "keine") "."
	//	"Stiefkinder:" (stiefkinder=Kinder? | "keine") "."
	//	"Beziehungen:" "{" (beziehungen+=Beziehung+ | "keine") "}"
	//	"Ereignisse:" "{" (ereignisse+=Ereignis+ | "keine" "bekannt")
	//	"}"
	//	"}";
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//Ereignis:
	//	Schulausbildung | Taetigkeit // | Lehre | Armeedienst | Unfall | Krankheit | NeueAdresse
	//;
	public EreignisElements getEreignisAccess() {
		return pEreignis;
	}
	
	public ParserRule getEreignisRule() {
		return getEreignisAccess().getRule();
	}
	
	//Schulausbildung:
	//	{Schulausbildung}
	//	"Schulausbildung:" "von" (von=DATUM? | "unbekannt") "bis" (bis=DATUM? | "unbekannt")
	//	"Abschluss:" (abschluss=STRING? | "ohne" | "abgebrochen")
	//	".";
	public SchulausbildungElements getSchulausbildungAccess() {
		return pSchulausbildung;
	}
	
	public ParserRule getSchulausbildungRule() {
		return getSchulausbildungAccess().getRule();
	}
	
	//Taetigkeit:
	//	{Taetigkeit}
	//	"Tätigkeit:" "als" (beruf=STRING? | "unbekannt")
	//	"bei" (arbeitgeber=STRING? | "unbekannt")
	//	"in" (ort=STRING? | "unbekannt")
	//	"von" (von=DATUM? | "unbekannt") "bis" (bis=DATUM? | "unbekannt") ".";
	public TaetigkeitElements getTaetigkeitAccess() {
		return pTaetigkeit;
	}
	
	public ParserRule getTaetigkeitRule() {
		return getTaetigkeitAccess().getRule();
	}
	
	//Kinder:
	//	{Kinder} (kind=[Person|STRING] | "unbekannt" | "unerfasst") ("," next=Kinder)?;
	public KinderElements getKinderAccess() {
		return pKinder;
	}
	
	public ParserRule getKinderRule() {
		return getKinderAccess().getRule();
	}
	
	//Beziehung:
	//	{Beziehung}
	//	"Beziehung:" "mit" (beziehung=[Person|STRING] | "unbekannt" | "unerfasst") "."
	//	"von:" (vonDatum=DATUM? | "unbekannt") "bis:" (bisDatum=DATUM? | "unbekannt" | "andauernd") "."
	//	"Hochzeit:" (hochzeitstag=DATUM? | "unbekannt" | "-") "."
	//	"Scheidung:" (scheidungstag=DATUM? | "unbekannt" | "unabsehbar" | "demnächst" | "-") ".";
	public BeziehungElements getBeziehungAccess() {
		return pBeziehung;
	}
	
	public ParserRule getBeziehungRule() {
		return getBeziehungAccess().getRule();
	}
	
	//Familienbuch:
	//	"Familienbuch" name=ID ";"
	//	"Familie:" familie=STRING "."
	//	"Person:" person=[Person|STRING] "."
	//	"Version:" version=VERSION "."
	//	"Titel:" titel=STRING "."
	//	"Vorwort:" "{" vorwort=STRING "}"
	//	"Autor:" "{" autor=Autor "}"
	//	"Familien:" "{"
	//	familien+=FamilienImport+
	//	"}";
	public FamilienbuchElements getFamilienbuchAccess() {
		return pFamilienbuch;
	}
	
	public ParserRule getFamilienbuchRule() {
		return getFamilienbuchAccess().getRule();
	}
	
	//FamilienImport:
	//	"import" "familie" familie=[Familie] '.';
	public FamilienImportElements getFamilienImportAccess() {
		return pFamilienImport;
	}
	
	public ParserRule getFamilienImportRule() {
		return getFamilienImportAccess().getRule();
	}
	
	//Autor:
	//	"Vorname:" vorname=STRING "."
	//	"Name:" nachname=STRING "."
	//	"Organisation" organisationsName=STRING? ".";
	public AutorElements getAutorAccess() {
		return pAutor;
	}
	
	public ParserRule getAutorRule() {
		return getAutorAccess().getRule();
	}
	
	//enum Geschlecht:
	//	unbekannt | maennlich='männlich'
	//	| weiblich;
	public GeschlechtElements getGeschlechtAccess() {
		return eGeschlecht;
	}
	
	public EnumRule getGeschlechtRule() {
		return getGeschlechtAccess().getRule();
	}
	
	//VERSION:
	//	INT "." INT "." INT;
	public VERSIONElements getVERSIONAccess() {
		return pVERSION;
	}
	
	public ParserRule getVERSIONRule() {
		return getVERSIONAccess().getRule();
	}
	
	//DATUM:
	//	DATE;
	public DATUMElements getDATUMAccess() {
		return pDATUM;
	}
	
	public ParserRule getDATUMRule() {
		return getDATUMAccess().getRule();
	}
	
	//terminal DATE returns ecore::EDate:
	//	'0'..'9' '0'..'9' '.' '0'..'9' '0'..'9' '.' '0'..'9' '0'..'9' '0'..'9' '0'..'9';
	public TerminalRule getDATERule() {
		return tDATE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
