/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ahnen.util;

import com.github.funthomas424242.dsl.ahnen.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see com.github.funthomas424242.dsl.ahnen.AhnenPackage
 * @generated
 */
public class AhnenSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static AhnenPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AhnenSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = AhnenPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case AhnenPackage.MODEL:
      {
        Model model = (Model)theEObject;
        T result = caseModel(model);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.DATEIART:
      {
        Dateiart dateiart = (Dateiart)theEObject;
        T result = caseDateiart(dateiart);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.FAMILIE:
      {
        Familie familie = (Familie)theEObject;
        T result = caseFamilie(familie);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.PERSON:
      {
        Person person = (Person)theEObject;
        T result = casePerson(person);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.EREIGNIS:
      {
        Ereignis ereignis = (Ereignis)theEObject;
        T result = caseEreignis(ereignis);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.SCHULAUSBILDUNG:
      {
        Schulausbildung schulausbildung = (Schulausbildung)theEObject;
        T result = caseSchulausbildung(schulausbildung);
        if (result == null) result = caseEreignis(schulausbildung);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.TAETIGKEIT:
      {
        Taetigkeit taetigkeit = (Taetigkeit)theEObject;
        T result = caseTaetigkeit(taetigkeit);
        if (result == null) result = caseEreignis(taetigkeit);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.KINDER:
      {
        Kinder kinder = (Kinder)theEObject;
        T result = caseKinder(kinder);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.BEZIEHUNG:
      {
        Beziehung beziehung = (Beziehung)theEObject;
        T result = caseBeziehung(beziehung);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.FAMILIENBUCH:
      {
        Familienbuch familienbuch = (Familienbuch)theEObject;
        T result = caseFamilienbuch(familienbuch);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.FAMILIEN_IMPORT:
      {
        FamilienImport familienImport = (FamilienImport)theEObject;
        T result = caseFamilienImport(familienImport);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AhnenPackage.AUTOR:
      {
        Autor autor = (Autor)theEObject;
        T result = caseAutor(autor);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Model</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseModel(Model object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dateiart</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dateiart</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDateiart(Dateiart object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Familie</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Familie</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFamilie(Familie object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePerson(Person object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ereignis</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ereignis</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEreignis(Ereignis object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Schulausbildung</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Schulausbildung</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSchulausbildung(Schulausbildung object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Taetigkeit</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Taetigkeit</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTaetigkeit(Taetigkeit object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Kinder</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Kinder</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseKinder(Kinder object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Beziehung</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Beziehung</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBeziehung(Beziehung object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Familienbuch</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Familienbuch</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFamilienbuch(Familienbuch object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Familien Import</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Familien Import</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFamilienImport(FamilienImport object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Autor</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Autor</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAutor(Autor object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //AhnenSwitch
