/*
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.validation

import com.github.funthomas424242.dsl.ahnen.AhnenPackage
import com.github.funthomas424242.dsl.ahnen.Beziehung
import com.github.funthomas424242.dsl.ahnen.Familie
import com.github.funthomas424242.dsl.ahnen.Kinder
import com.github.funthomas424242.dsl.ahnen.Person
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class AhnenValidator extends AbstractAhnenValidator {
	
	
	@Check
	def void checkFamilyConsistence(Familie familie){
	    var Kinder kinder = familie.kinder;
	    while(kinder.kind != null){
	        checkKindBackRefToFamily(familie,kinder.kind);
	        kinder=kinder.next;
	    }
	}
	
    def void checkKindBackRefToFamily(Familie familie, Person kind){
        
        if( kind.beziehungen == null || kind.beziehungen.empty){
         warning("Person: "+kind.name+" benötigt eine Beziehung zur Familie: "+familie.name
               ,AhnenPackage.Literals.FAMILIE__KINDER
         );
         return;
        }
         var boolean hasBackLink = false;
         for( Beziehung beziehung: kind.beziehungen){
            if( beziehung.beziehung != null &&
                beziehung.beziehung != "unbekannt" &&
                beziehung.beziehung != "unerfasst" &&
                beziehung.beziehung instanceof Familie && 
                beziehung.beziehung.name.equals(familie.name)
            ){
                hasBackLink = true;
            } 
         }
         if( !hasBackLink ){
           warning("Person: "+kind.name+" benötigt eine Beziehung zur Familie: "+familie.name
               ,AhnenPackage.Literals.FAMILIE__KINDER
           );
         }
    }
	
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					AhnenPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
