/*
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AhnenStandaloneSetup extends AhnenStandaloneSetupGenerated {

	def static void doSetup() {
		new AhnenStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
