/**
 * generated by Xtext 2.10.0
 */
package com.github.funthomas424242.dsl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class AhnenQuickfixProvider extends DefaultQuickfixProvider {
}
